const {sb,$,msg,pt,S,esc}=window.C;
const SUPA='https://nxjdnzdxclszqyqrkwdk.supabase.co';
const KEY='sb_publishable_BCa63l0nMBLzOOHLZPpxfg_Ep2CqYdU';
const state={photoBusy:false,repairBusy:false,researchBusy:false};
function style(){if(document.getElementById('v9style'))return;const s=document.createElement('style');s.id='v9style';s.textContent=`
#photoMsg,#researchNowMsg{margin-top:9px}.cv-clean{display:grid;gap:12px}.cv-topline{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.cv-badge{display:inline-flex;gap:7px;align-items:center;padding:7px 10px;border-radius:999px;background:#ecfdf3;color:#067647;font-size:12px;font-weight:900}.cv-badge.warn{background:#fff7e8;color:#9a5a00}.cv-mini{font-size:12px;color:#667085}.cv-understood{padding:14px;border:1px solid #e6e9f0;background:#fff;border-radius:14px}.cv-understood h4{margin:0 0 8px}.cv-counts{display:flex;gap:7px;flex-wrap:wrap;margin:8px 0}.cv-count{padding:6px 9px;border-radius:999px;background:#f0ecff;color:#5637e6;font-size:12px;font-weight:800}.cv-content{display:grid;gap:10px;margin-top:10px}.cv-part{padding-top:10px;border-top:1px solid #eef0f4}.cv-part strong{display:block;margin-bottom:5px}.cv-part p,.cv-part ul{margin:0;color:#475467;line-height:1.5}.cv-part ul{padding-left:20px}.cv-attention{padding:12px;border-radius:12px;background:#fff7e8;color:#8a4b00;border:1px solid #ffe1a8;line-height:1.45}.cv-ready{padding:12px;border-radius:12px;background:#ecfdf3;color:#067647;line-height:1.45}.cv-replace{margin-top:12px;border-top:1px solid #eef0f4;padding-top:12px}.cv-replace summary{cursor:pointer;font-weight:850;color:#475467}.radar-now{margin-top:14px;padding:14px;border:1px solid #ddd6ff;border-radius:14px;background:#fff}.radar-now-row{display:flex;align-items:center;gap:12px;justify-content:space-between}.radar-now-copy{flex:1}.radar-now-copy strong{display:block;margin-bottom:3px}.photo-selected{outline:3px solid #dcd5ff}.photo-status{font-size:12px;color:#667085;margin-top:6px}.btn.busy{opacity:.72;cursor:wait}@media(max-width:720px){.cv-topline,.radar-now-row{display:grid}.radar-now-row .btn{width:100%}}
`;document.head.appendChild(s)}
const ev=v=>v&&typeof v==='object'&&'value'in v?v.value:v;
const list=(v,max=8)=>Array.isArray(v)?v.map(ev).filter(Boolean).slice(0,max):[];
function draftStats(dr={}){return{summary:ev(dr.summary)||'',experience:list(dr.experience_evidence,100),education:list(dr.education_evidence,60),skills:list(dr.skills_evidence,60),languages:list(dr.languages_evidence,30),certifications:list(dr.certifications_evidence,50)}}
function meaningful(x){return Boolean(x.summary||x.experience.length||x.education.length||x.skills.length||x.languages.length||x.certifications.length)}
function cvPart(title,items){return items.length?`<div class="cv-part"><strong>${esc(title)}</strong><ul>${items.slice(0,8).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${items.length>8?`<p class="cv-mini">+ ${items.length-8} item(ns)</p>`:''}</div>`:''}
async function getCvData(){if(!S.session)return null;const uid=S.session.user.id;const [d,r]=await Promise.all([sb.from('career_documents').select('id,original_filename_display,file_status,parser_version,created_at,deleted_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(5),sb.from('career_profile_drafts').select('id,document_id,status,draft_json,parser_version,created_at,confirmed_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(5)]);return{docs:d.data||[],drafts:r.data||[]}}
function ensureReplaceDetails(){const late=$('lateCv');if(!late||document.getElementById('cvReplaceDetails'))return;const f=late.closest('.f'),btn=$('lateCvGo'),m=$('lateCvMsg');if(!f||!btn)return;const details=document.createElement('details');details.id='cvReplaceDetails';details.className='cv-replace';details.innerHTML='<summary>Trocar ou reenviar currículo</summary>';f.parentNode.insertBefore(details,f);details.appendChild(f);details.appendChild(btn);if(m)details.appendChild(m);const label=f.querySelector('label');if(label)label.textContent='Escolher outro currículo';try{late.value=''}catch{}}
function renderCv(data){const box=$('cvStatusBox');if(!box||!data)return;const doc=data.docs[0],draft=data.drafts[0],st=draftStats(draft?.draft_json||{}),ok=meaningful(st);if(!doc){box.innerHTML='<div class="cv-clean"><div class="cv-attention"><strong>Nenhum currículo conectado.</strong><br>Adicione um PDF textual ou DOCX para o Career organizar sua trajetória.</div></div>';return}
const status=draft?.status==='confirmed'?'confirmed':draft?.status==='requires_confirmation'?'review':'received';const badge=status==='confirmed'?'<span class="cv-badge">✓ Dados confirmados</span>':status==='review'?'<span class="cv-badge warn">Revisão necessária</span>':'<span class="cv-badge warn">Arquivo recebido</span>';
let body='';if(ok){body=`<div class="cv-understood"><h4>O que o Career entendeu do seu currículo</h4><div class="cv-counts">${st.summary?'<span class="cv-count">Resumo</span>':''}${st.experience.length?`<span class="cv-count">Experiência ${st.experience.length}</span>`:''}${st.education.length?`<span class="cv-count">Formação ${st.education.length}</span>`:''}${st.skills.length?`<span class="cv-count">Competências ${st.skills.length}</span>`:''}${st.languages.length?`<span class="cv-count">Idiomas ${st.languages.length}</span>`:''}${st.certifications.length?`<span class="cv-count">Certificações ${st.certifications.length}</span>`:''}</div><div class="cv-content">${st.summary?`<div class="cv-part"><strong>Resumo profissional encontrado</strong><p>${esc(st.summary)}</p></div>`:''}${cvPart('Experiência',st.experience)}${cvPart('Formação',st.education)}${cvPart('Competências',st.skills)}${cvPart('Idiomas',st.languages)}${cvPart('Cursos e certificações',st.certifications)}</div></div>`}else{body='<div class="cv-attention"><strong>O arquivo foi recebido, mas o conteúdo ainda não foi estruturado com qualidade suficiente.</strong><br>O Career não deve chamar isso de “currículo entendido”. Estou reprocessando com o parser atualizado.</div>'}
box.innerHTML=`<div class="cv-clean"><div class="cv-topline"><div><strong>${esc(doc.original_filename_display)}</strong><div class="cv-mini">Recebido em ${new Date(doc.created_at).toLocaleString('pt-BR')}</div></div>${badge}</div>${body}${status==='confirmed'&&ok?'<div class="cv-ready">✓ Essas informações estão confirmadas e disponíveis para o Perfil Profissional e para o agente.</div>':status==='review'&&ok?'<div class="cv-attention">Revise os dados acima e confirme antes que o agente os trate como fatos da sua carreira.</div>':''}<div class="cv-mini">O arquivo original é removido após a confirmação quando aplicável; os dados estruturados confirmados permanecem no seu perfil.</div></div>`;
if(status==='review'&&ok){S.draft=draft.id;S.parsed=draft.draft_json;$('confirmCv').classList.remove('hide');$('cvDraftPreview').classList.add('hide')}else if(status==='confirmed'){$('confirmCv').classList.add('hide');$('cvDraftPreview').classList.add('hide')}}
async function repairCvIfNeeded(){if(state.repairBusy||!S.session)return;const data=await getCvData();if(!data)return;const newest=data.drafts[0],stats=draftStats(newest?.draft_json||{});if(meaningful(stats)){renderCv(data);return}const retained=data.docs.find(d=>!d.deleted_at&&d.file_status!=='deleted');if(!retained){renderCv(data);return}if(retained.parser_version==='career360-edge-parser/1.0.2'){renderCv(data);return}state.repairBusy=true;const box=$('cvStatusBox');if(box)box.innerHTML='<div class="cv-attention"><strong>Reprocessando seu currículo...</strong><br>Encontramos uma extração antiga incompleta e estamos corrigindo sem pedir novo upload.</div>';try{const r=await sb.functions.invoke('career-document-process',{body:{document_id:retained.id}});if(r.error)throw r.error;S.draft=r.data?.draft_id;S.parsed=r.data?.candidate_profile_draft||null;const fresh=await getCvData();renderCv(fresh);if(r.data?.status==='EXTRACTION_INSUFFICIENT')msg('lateCvMsg','O PDF foi lido, mas ainda faltam seções estruturáveis. Você pode reenviar outro formato ou revisar manualmente.','warn');else msg('lateCvMsg','✓ Currículo reprocessado com o parser atualizado. Revise os dados e confirme.','ok')}catch(e){renderCv(data);msg('lateCvMsg',pt(e.message||'Não consegui reprocessar agora.'),'bad')}finally{state.repairBusy=false}}
async function session(){return(await sb.auth.getSession()).data.session}
async function rawPhotoUpload(file){const s=await session();if(!s)throw new Error('AUTH_REQUIRED');const fd=new FormData();fd.append('file',file,file.name);const r=await fetch(`${SUPA}/functions/v1/career-profile-photo`,{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`,apikey:KEY},body:fd});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`HTTP_${r.status}`);return d}
function ensurePhotoMsg(){if($('photoMsg'))return $('photoMsg');const p=document.createElement('div');p.id='photoMsg';p.className='msg hide';const helper=$('profilePhotoFile')?.closest('.photo-controls')?.nextElementSibling;if(helper)helper.parentNode.insertBefore(p,helper.nextSibling);else $('professionalV8')?.appendChild(p);return p}
async function uploadPhotoNow(){if(state.photoBusy)return;const input=$('profilePhotoFile'),file=input?.files?.[0];ensurePhotoMsg();if(!file)return msg('photoMsg','Escolha uma foto para continuar.','warn');if(file.size>5*1024*1024)return msg('photoMsg','A foto deve ter no máximo 5 MB.','warn');if(!/^image\/(jpeg|png|webp)$/.test(file.type||''))return msg('photoMsg','Use uma foto JPG, PNG ou WebP.','warn');const img=$('profilePhotoImg'),fallback=$('profilePhotoFallback'),btn=$('uploadPhoto');const local=URL.createObjectURL(file);if(img){img.src=local;img.classList.remove('hide');img.classList.add('photo-selected')}fallback?.classList.add('hide');state.photoBusy=true;if(btn){btn.disabled=true;btn.classList.add('busy');btn.textContent='Enviando foto...'}msg('photoMsg','Enviando e protegendo sua foto...','');try{const d=await rawPhotoUpload(file);if(!d?.photo?.url)throw new Error('PHOTO_URL_MISSING');if(img){img.onload=()=>img.classList.remove('photo-selected');img.onerror=()=>msg('photoMsg','A foto foi enviada, mas a visualização falhou. Recarregue a página.','warn');img.src=d.photo.url;img.classList.remove('hide')}fallback?.classList.add('hide');$('removePhoto')?.classList.remove('hide');msg('photoMsg','✓ Foto carregada com sucesso. Ela continua fora do matching.','ok');try{input.value=''}catch{}}catch(e){if(img){img.classList.add('hide');img.classList.remove('photo-selected')}fallback?.classList.remove('hide');msg('photoMsg',pt(e.message||'Não consegui enviar a foto.'),'bad')}finally{URL.revokeObjectURL(local);state.photoBusy=false;if(btn){btn.disabled=false;btn.classList.remove('busy');btn.textContent='Adicionar foto'}}}
function wirePhoto(){const input=$('profilePhotoFile'),btn=$('uploadPhoto');if(!input||!btn||input.dataset.v9==='1')return;input.dataset.v9='1';ensurePhotoMsg();btn.onclick=uploadPhotoNow;input.addEventListener('change',()=>{if(input.files?.[0])uploadPhotoNow()})}
function ensureRadarButton(){const box=$('opps')?.querySelector('.radarbox');if(!box||$('researchNow'))return;const wrap=document.createElement('div');wrap.className='radar-now';wrap.innerHTML='<div class="radar-now-row"><div class="radar-now-copy"><strong>Pesquisa ativa do Radar</strong><span class="muted">Faça uma nova varredura das fontes conectadas agora. O Career filtra antes de mostrar qualquer vaga.</span></div><button id="researchNow" class="btn" type="button">🔎 Pesquisar oportunidades agora</button></div><div id="researchNowMsg" class="msg hide"></div>';box.appendChild(wrap);$('researchNow').onclick=runResearchNow}
async function refreshRadar(){try{const r=await sb.functions.invoke('career-opportunity-list',{body:{limit:50}});if(r.error)throw r.error;const w=r.data?.work_summary||{};$('m1').textContent=String(w.analyzed_total??0);$('m2').textContent=String(w.qualified_total??0);$('m4').textContent=String(w.discarded_total??0);const listBox=$('oppList'),items=r.data?.items||[];if(listBox)listBox.innerHTML='<h2>Seu radar</h2>'+(items.length?items.map(x=>`<div class="opp"><span class="score">${Math.round(Number(x.score||0))}%</span> · <strong>${esc(x.opportunity?.title||'Oportunidade')}</strong><br><span class="muted">${esc(x.opportunity?.employer_name||'Empresa')} · ${esc(x.classification)}</span></div>`).join(''):`<div class="emptyradar"><strong>Nenhuma oportunidade qualificada ainda.</strong><p class="muted">O agente já analisou ${w.analyzed_total||0} oportunidade(s) e descartou ${w.discarded_total||0}. Só o que passa pelos filtros aparece aqui.</p></div>`);return w}catch{return null}}
async function runResearchNow(){if(state.researchBusy)return;state.researchBusy=true;const b=$('researchNow');if(b){b.disabled=true;b.classList.add('busy');b.textContent='Pesquisando agora...'}msg('researchNowMsg','Consultando as fontes conectadas e recalculando seu radar...','');try{const r=await sb.functions.invoke('career-opportunity-refresh-now',{body:{source_limit:10}});if(r.error)throw r.error;const totals=r.data?.totals;if(r.data?.status==='RESEARCH_COMPLETE'&&totals){msg('researchNowMsg',`✓ Pesquisa concluída: ${totals.sources} fonte(s), ${totals.fetched} vagas lidas, ${totals.accepted} nova(s) e ${totals.deduped} já conhecidas.`,'ok')}else msg('researchNowMsg',r.data?.message||'Pesquisa iniciada. O radar será atualizado automaticamente.','ok');await refreshRadar()}catch(e){const t=String(e.message||'');msg('researchNowMsg',t.includes('429')||t.includes('cooldown')?'Uma pesquisa já foi iniciada há poucos instantes. Aguarde a atualização do radar.':pt(t||'Não consegui pesquisar agora.'),'warn')}finally{state.researchBusy=false;if(b){b.disabled=false;b.classList.remove('busy');b.textContent='🔎 Pesquisar oportunidades agora'}}}
function init(){style();ensureReplaceDetails();wirePhoto();ensureRadarButton();setTimeout(repairCvIfNeeded,500);setTimeout(refreshRadar,700);$('confirmCv')?.addEventListener('click',()=>setTimeout(repairCvIfNeeded,2600));document.querySelector('[data-v="career"]')?.addEventListener('click',()=>setTimeout(()=>{wirePhoto();repairCvIfNeeded()},300));document.querySelector('[data-v="opps"]')?.addEventListener('click',()=>setTimeout(()=>{ensureRadarButton();refreshRadar()},250))}
sb.auth.onAuthStateChange((_,s)=>{if(s){S.session=s;setTimeout(init,500)}});const ss=await session();if(ss){S.session=ss;init()}
