const {sb,$,esc}=window.C;
const SUPA='https://nxjdnzdxclszqyqrkwdk.supabase.co';
const KEY='sb_publishable_BCa63l0nMBLzOOHLZPpxfg_Ep2CqYdU';
const PS={state:null,processing:false};

function css(){if($('photoStudioStyle'))return;const s=document.createElement('style');s.id='photoStudioStyle';s.textContent=`
.photo-studio-btn{border:0;background:rgba(255,255,255,.96);box-shadow:0 7px 22px rgba(24,18,51,.13);border-radius:999px;padding:8px 11px;font-size:11px;font-weight:900;color:#5639df;cursor:pointer;white-space:nowrap}.photo-studio-wrap{position:relative}.photo-studio-badge{position:absolute;right:-3px;bottom:-3px}.photo-studio-modal{position:fixed;inset:0;background:rgba(17,13,31,.56);z-index:120;display:none;align-items:flex-end;justify-content:center;padding:16px}.photo-studio-modal.on{display:flex}.photo-studio-panel{width:min(780px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:26px;padding:22px;box-shadow:0 22px 70px rgba(11,8,27,.3)}.photo-studio-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.photo-studio-head h2{margin:0 0 6px;font-size:22px}.photo-studio-close{border:0;background:#f2f4f7;width:38px;height:38px;border-radius:50%;font-size:19px;cursor:pointer}.photo-studio-context{margin-top:14px;padding:13px 14px;border:1px solid #e9e5ff;border-radius:15px;background:#faf9ff;font-size:12px;color:#4a4560;line-height:1.5}.photo-style-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:15px}.photo-style{border:1px solid #e6e7ed;background:#fff;border-radius:14px;padding:11px;text-align:left;cursor:pointer;min-height:76px}.photo-style.on{border-color:#6a4df4;background:#f6f3ff;box-shadow:0 0 0 2px rgba(106,77,244,.08)}.photo-style b{display:block;font-size:12px}.photo-style span{display:block;color:#667085;font-size:10.5px;line-height:1.35;margin-top:4px}.photo-studio-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.photo-compare{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:18px}.photo-frame{border:1px solid #e6e7ed;border-radius:18px;padding:10px;background:#fafbfc}.photo-frame label{display:block;font-size:11px;font-weight:900;color:#667085;margin:0 0 7px 2px}.photo-frame img,.photo-frame canvas{width:100%;aspect-ratio:4/5;object-fit:cover;border-radius:13px;background:#edf0f4;display:block}.photo-studio-note{font-size:11px;color:#667085;line-height:1.5;margin-top:12px}.photo-studio-msg{margin-top:12px;font-size:12px;font-weight:750}.photo-studio-msg.ok{color:#067647}.photo-studio-msg.bad{color:#b42318}.photo-studio-active{display:inline-flex;align-items:center;gap:6px;margin-top:8px;padding:6px 9px;border-radius:999px;background:#ecfdf3;color:#067647;font-size:10.5px;font-weight:900}@media(max-width:720px){.photo-studio-modal{padding:0}.photo-studio-panel{border-radius:25px 25px 0 0;max-height:94vh;padding:18px}.photo-style-grid{grid-template-columns:1fr 1fr}.photo-compare{grid-template-columns:1fr}.photo-studio-actions .btn{flex:1}}
`;document.head.appendChild(s)}

async function sess(){return(await sb.auth.getSession()).data.session}
async function studio(action=null,body={}){const se=await sess();if(!se)throw new Error('AUTH_REQUIRED');if(!action){const r=await fetch(`${SUPA}/functions/v1/career-photo-studio`,{headers:{Authorization:`Bearer ${se.access_token}`,apikey:KEY}});if(!r.ok)throw new Error('PHOTO_STUDIO_FAILED');return r.json()}const r=await fetch(`${SUPA}/functions/v1/career-photo-studio`,{method:'POST',headers:{Authorization:`Bearer ${se.access_token}`,apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({action,...body})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'PHOTO_STUDIO_FAILED');return d}
async function uploadVariant(blob,style){const se=await sess();if(!se)throw new Error('AUTH_REQUIRED');const fd=new FormData();fd.append('file',new File([blob],'professional.jpg',{type:'image/jpeg'}));fd.append('style_key',style);const r=await fetch(`${SUPA}/functions/v1/career-photo-studio`,{method:'POST',headers:{Authorization:`Bearer ${se.access_token}`,apikey:KEY},body:fd});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'VARIANT_UPLOAD_FAILED');return d}

function ensureModal(){if($('photoStudioModal'))return;const m=document.createElement('div');m.id='photoStudioModal';m.className='photo-studio-modal';m.innerHTML=`<div class="photo-studio-panel"><div class="photo-studio-head"><div><div class="showcase-kicker">Estúdio de Foto Profissional</div><h2>Uma versão mais profissional da sua foto</h2><p class="muted" style="margin:0">Ajustamos apresentação, enquadramento, fundo e luz. Sua identidade continua sendo você.</p></div><button id="photoStudioClose" class="photo-studio-close" type="button">×</button></div><div id="photoStudioContext" class="photo-studio-context"></div><div id="photoStyles" class="photo-style-grid"></div><div id="photoStudioCompare" class="photo-compare"></div><div id="photoStudioActions" class="photo-studio-actions"></div><div id="photoStudioMsg" class="photo-studio-msg"></div><div class="photo-studio-note">🔒 A foto não entra no matching nem altera seu FIT. A versão original é preservada. Uma versão profissional só vira sua foto principal depois da sua aprovação.</div></div>`;document.body.appendChild(m);$('photoStudioClose').onclick=close;m.addEventListener('click',e=>{if(e.target===m)close()})}
function close(){$('photoStudioModal')?.classList.remove('on')}
const styles={executive:{label:'Executivo',desc:'Sóbrio e contemporâneo'},corporate:{label:'Corporativo',desc:'Natural e acessível'},modern:{label:'Moderno',desc:'Limpo e atual'},creative:{label:'Expressivo',desc:'Profissional com personalidade'}};
function selectedStyle(){return document.querySelector('.photo-style.on')?.dataset.style||PS.state?.recommendation?.key||'corporate'}
function render(){ensureModal();const st=PS.state;if(!st)return;const c=st.career_context||{},rec=st.recommendation||{};$('photoStudioContext').innerHTML=`<strong>Recomendação do Career: ${esc(rec.label||'Corporativo natural')}</strong><br>${esc(rec.reason||'Ajuste profissional compatível com seu perfil.')} ${c.target_roles?.length?`<br><span class="muted">Direcionamento: ${c.target_roles.map(esc).join(' · ')}</span>`:''}`;$('photoStyles').innerHTML=Object.entries(styles).map(([k,v])=>`<button type="button" class="photo-style ${k===rec.key?'on':''}" data-style="${k}"><b>${v.label}${k===rec.key?' · recomendado':''}</b><span>${v.desc}</span></button>`).join('');document.querySelectorAll('.photo-style').forEach(b=>b.onclick=()=>{document.querySelectorAll('.photo-style').forEach(x=>x.classList.remove('on'));b.classList.add('on')});const orig=st.original?.url,active=st.active_variant?.url,latest=(st.variants||[]).find(v=>v.status==='ready'&&v.url)?.url;const right=latest||active;$('photoStudioCompare').innerHTML=`<div class="photo-frame"><label>Original</label>${orig?`<img src="${esc(orig)}" alt="Foto original">`:'<div class="muted">Adicione uma foto primeiro.</div>'}</div><div class="photo-frame"><label>${right?'Versão profissional':'Prévia profissional'}</label>${right?`<img src="${esc(right)}" alt="Versão profissional">`:'<canvas id="photoStudioCanvas" width="900" height="1125"></canvas>'}</div>`;const variant=(st.variants||[]).find(v=>v.status==='ready'&&v.url);$('photoStudioActions').innerHTML=orig?`${variant?`<button id="photoAccept" class="btn" type="button">Usar versão profissional</button><button id="photoRetry" class="btn sec" type="button">Tentar outro estilo</button>`:`<button id="photoCreate" class="btn" type="button">Criar versão profissional</button>`}${active?`<button id="photoOriginal" class="btn sec" type="button">Voltar para original</button>`:''}`:'<button class="btn sec" type="button" disabled>Adicione uma foto primeiro</button>';if(active)$('photoStudioContext').insertAdjacentHTML('beforeend','<div class="photo-studio-active">✓ Versão profissional em uso</div>');if($('photoCreate'))$('photoCreate').onclick=createProfessional;if($('photoRetry'))$('photoRetry').onclick=createProfessional;if($('photoAccept'))$('photoAccept').onclick=()=>accept(variant.id);if($('photoOriginal'))$('photoOriginal').onclick=useOriginal}

async function open(){ensureModal();$('photoStudioModal').classList.add('on');msg('Carregando...');try{PS.state=await studio();render();msg('')}catch{msg('Não consegui abrir o Estúdio agora.','bad')}}
function msg(t,cls='') {const e=$('photoStudioMsg');if(e){e.textContent=t;e.className='photo-studio-msg '+cls}}
function addButtons(){const avatars=[...document.querySelectorAll('.my-avatar,.showcase-avatar')];avatars.forEach(a=>{if(a.closest('.photo-studio-wrap'))return;const w=document.createElement('div');w.className='photo-studio-wrap';a.parentNode.insertBefore(w,a);w.appendChild(a);const b=document.createElement('button');b.type='button';b.className='photo-studio-btn photo-studio-badge';b.textContent='✨ Melhorar foto';b.onclick=open;w.appendChild(b)})}

function loadScript(){return new Promise((resolve,reject)=>{if(window.SelfieSegmentation)return resolve(window.SelfieSegmentation);const old=document.querySelector('script[data-career-seg]');if(old){old.addEventListener('load',()=>resolve(window.SelfieSegmentation));old.addEventListener('error',reject);return}const s=document.createElement('script');s.dataset.careerSeg='1';s.src='https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation.js';s.onload=()=>resolve(window.SelfieSegmentation);s.onerror=reject;document.head.appendChild(s)})}
function loadImg(url){return new Promise((resolve,reject)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>resolve(i);i.onerror=reject;i.src=url})}
function crop(img,w,h){const ar=w/h,iar=img.naturalWidth/img.naturalHeight;let sx=0,sy=0,sw=img.naturalWidth,sh=img.naturalHeight;if(iar>ar){sw=img.naturalHeight*ar;sx=(img.naturalWidth-sw)/2}else{sh=img.naturalWidth/ar;sy=Math.max(0,(img.naturalHeight-sh)*0.28)}return{sx,sy,sw,sh}}
function bg(ctx,w,h,style){const palettes={executive:['#f8fafc','#dce3ea'],corporate:['#faf9f7','#e8e5df'],modern:['#f5f8fb','#dfe7ee'],creative:['#faf7fc','#e9e3f1']};const p=palettes[style]||palettes.corporate,g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,p[0]);g.addColorStop(1,p[1]);ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
async function polish(url,style){await loadScript();const img=await loadImg(url);const Seg=window.SelfieSegmentation;if(!Seg)throw new Error('SEGMENTATION_UNAVAILABLE');const seg=new Seg({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/${f}`});seg.setOptions({modelSelection:1});const W=900,H=1125,c=document.createElement('canvas');c.width=W;c.height=H;const ctx=c.getContext('2d');if(!ctx)throw new Error('CANVAS_UNAVAILABLE');const cr=crop(img,W,H);await new Promise((resolve,reject)=>{seg.onResults(r=>{try{ctx.clearRect(0,0,W,H);ctx.save();ctx.drawImage(r.segmentationMask,cr.sx,cr.sy,cr.sw,cr.sh,0,0,W,H);ctx.globalCompositeOperation='source-in';ctx.filter=style==='executive'?'brightness(1.04) contrast(1.05) saturate(.96)':style==='modern'?'brightness(1.05) contrast(1.04) saturate(.98)':'brightness(1.04) contrast(1.03) saturate(.97)';ctx.drawImage(r.image,cr.sx,cr.sy,cr.sw,cr.sh,0,0,W,H);ctx.filter='none';ctx.globalCompositeOperation='destination-over';bg(ctx,W,H,style);ctx.restore();resolve()}catch(e){reject(e)}});seg.send({image:img}).catch(reject)});try{seg.close()}catch{}return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('ENCODE_FAILED')),'image/jpeg',.92))}
async function createProfessional(){if(PS.processing)return;PS.processing=true;const style=selectedStyle(),b=$('photoCreate')||$('photoRetry');if(b){b.disabled=true;b.textContent='Preparando...'}msg('Ajustando enquadramento, fundo e luz no seu dispositivo...');try{const blob=await polish(PS.state.original.url,style);await uploadVariant(blob,style);PS.state=await studio();render();msg('Versão pronta. Compare e escolha qual deseja usar.','ok')}catch(e){msg('Não consegui preparar a versão profissional neste dispositivo. Sua foto original continua intacta.','bad')}finally{PS.processing=false}}
async function accept(id){msg('Aplicando sua escolha...');try{PS.state=await studio('accept',{variant_id:id});render();msg('✓ Versão profissional escolhida. A original continua preservada.','ok');document.dispatchEvent(new CustomEvent('career-photo-changed'))}catch{msg('Não consegui aplicar a versão agora.','bad')}}
async function useOriginal(){try{PS.state=await studio('use_original');render();msg('Foto original voltou a ser a principal.','ok');document.dispatchEvent(new CustomEvent('career-photo-changed'))}catch{msg('Não consegui alterar agora.','bad')}}

function observe(){const root=$('app');if(!root)return;let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(addButtons,120)}).observe(root,{childList:true,subtree:true});addButtons()}
css();ensureModal();observe();document.addEventListener('career-photo-changed',()=>setTimeout(()=>location.reload(),450));sb.auth.onAuthStateChange((_,s)=>{if(s)setTimeout(addButtons,500)});
