const {sb,$,esc}=window.C;
const P={status:null,loading:false};
function style(){if($('proactiveStyle'))return;const s=document.createElement('style');s.id='proactiveStyle';s.textContent=`
.proactive-card{padding:18px}.proactive-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.proactive-head h3{margin:0}.proactive-sub{font-size:13px;color:#667085;margin-top:4px;line-height:1.45}.proactive-pulse{display:inline-flex;align-items:center;gap:7px;font-size:12px;font-weight:850;color:#067647;background:#ecfdf3;padding:6px 9px;border-radius:999px}.proactive-pulse:before{content:'';width:8px;height:8px;border-radius:50%;background:#12b76a}.proactive-summary{margin-top:14px;padding:14px;border:1px solid #ebeaf4;border-radius:14px;background:#fcfcff}.proactive-summary strong{display:block;margin-bottom:6px}.proactive-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.proactive-metric{padding:10px;border-radius:12px;background:#f7f5ff}.proactive-metric span{display:block;font-size:10px;color:#667085}.proactive-metric b{font-size:20px}.proactive-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.proactive-alert{margin-top:10px;padding:12px 13px;border-radius:13px;border:1px solid #f6d7a7;background:#fffaf2}.proactive-alert.critical{border-color:#f3b4b4;background:#fff5f5}.proactive-alert-title{font-weight:850;font-size:13px}.proactive-alert-body{font-size:12px;line-height:1.45;color:#475467;margin-top:4px}.agent-badge{display:inline-grid;place-items:center;min-width:18px;height:18px;padding:0 5px;border-radius:999px;background:#6947f6;color:#fff;font-size:10px;font-weight:900;margin-left:5px}@media(max-width:720px){.proactive-grid{grid-template-columns:repeat(2,1fr)}.proactive-head{display:block}.proactive-pulse{margin-top:8px}}
`;document.head.appendChild(s)}
function fmt(iso){if(!iso)return'—';return new Date(iso).toLocaleString('pt-BR',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'})}
async function loadStatus(action=null,id=null){if(P.loading)return;P.loading=true;try{const body=action?{action,notification_id:id}:{};const r=await sb.functions.invoke('career-proactive-status',{body});if(r.error)throw r.error;P.status=r.data||null;render();badge()}catch{}finally{P.loading=false}}
async function updateNow(){const b=$('proactiveNow');if(b){b.disabled=true;b.textContent='Atualizando...'}try{const se=(await sb.auth.getSession()).data.session;if(!se)throw new Error('AUTH');const r=await fetch('https://nxjdnzdxclszqyqrkwdk.supabase.co/functions/v1/career-proactive-digest',{method:'POST',headers:{Authorization:`Bearer ${se.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'generate_now'})});if(!r.ok)throw new Error('FAILED');await loadStatus()}catch{}finally{if(b){b.disabled=false;b.textContent='Atualizar agora'}}}
function badge(){const btn=document.querySelector('[data-v="agent"]');if(!btn||!P.status)return;btn.querySelector('.agent-badge')?.remove();const n=Number(P.status.unread_count||0);if(n>0){const x=document.createElement('span');x.className='agent-badge';x.textContent=n>9?'9+':String(n);btn.appendChild(x)}}
function render(){const home=$('home');if(!home||!P.status)return;let card=$('proactiveCard');if(!card){card=document.createElement('div');card.id='proactiveCard';card.className='card proactive-card';const radar=$('radarCompact');if(radar?.parentNode)radar.parentNode.insertBefore(card,radar.nextSibling);else home.appendChild(card)}const s=P.status,d=s.latest_digest?.summary_json||{},p=s.preference||{};const unread=(s.notifications||[]).filter(x=>x.status==='unread');const alerts=unread.filter(x=>x.kind==='critical'||x.kind==='action_required').slice(0,3);const last=s.latest_digest?fmt(s.latest_digest.generated_at):'ainda sem resumo';const next=p.next_digest_at?fmt(p.next_digest_at):'—';card.innerHTML=`<div class="proactive-head"><div><h3>Atualizações do seu agente</h3><div class="proactive-sub">Resumo automático a cada ${Number(p.cadence_hours||12)}h · última atualização ${esc(last)} · próxima prevista ${esc(next)}</div></div><div class="proactive-pulse">Agente trabalhando</div></div><div class="proactive-summary"><strong>${s.latest_digest?'Desde a última atualização':'Seu primeiro resumo aparecerá aqui'}</strong><div class="proactive-grid"><div class="proactive-metric"><span>Analisadas</span><b>${Number(d.analyzed||0)}</b></div><div class="proactive-metric"><span>Qualificadas</span><b>${Number(d.qualified||0)}</b></div><div class="proactive-metric"><span>Candidaturas</span><b>${Number(d.applied||0)}</b></div><div class="proactive-metric"><span>Respostas</span><b>${Number(d.replies||0)}</b></div></div><div class="proactive-actions"><button id="proactiveNow" class="btn sec" type="button">Atualizar agora</button></div></div>${alerts.map(x=>`<div class="proactive-alert ${x.kind==='critical'?'critical':''}"><div class="proactive-alert-title">${esc(x.title||'Atualização importante')}</div><div class="proactive-alert-body">${esc(x.body||'')}</div><button class="tinybtn proactive-read" data-id="${esc(x.id)}" type="button" style="margin-top:8px">Marcar como lido</button></div>`).join('')}`;$('proactiveNow').onclick=updateNow;card.querySelectorAll('.proactive-read').forEach(b=>b.onclick=()=>loadStatus('mark_read',b.dataset.id))}
function observe(){const root=$('app');if(!root)return;let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>{render();badge()},120)}).observe(root,{childList:true,subtree:true})}
style();observe();sb.auth.onAuthStateChange((_,sess)=>{if(sess)setTimeout(()=>loadStatus(),500)});const se=(await sb.auth.getSession()).data.session;if(se)await loadStatus();setInterval(()=>{if(!$('app')?.classList.contains('hide'))loadStatus()},60000);
