import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.114.0/+esm';
const URL='https://nxjdnzdxclszqyqrkwdk.supabase.co',KEY='sb_publishable_BCa63l0nMBLzOOHLZPpxfg_Ep2CqYdU',APP='https://lsi-career-360.vercel.app/';
const sb=createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),$=x=>document.getElementById(x),csv=x=>String(x||'').split(',').map(v=>v.trim()).filter(Boolean);
const F={ing:'career-document-ingest',pro:'career-document-process',con:'career-profile-confirm',add:'career-opportunity-add',list:'career-opportunity-list',ag:'career-agent',sup:'career-support',mas:'career-master-status',emp:'career-employer-suggest'};
let mode='login',S={session:null,role:'candidate',profile:null,prefs:null,blocks:[],skills:[],docs:[],cvDraft:null,opps:[],draft:null,parsed:null,step:1,skillSelected:new Set()};
function msg(id,t,k=''){let e=$(id);if(!e)return;e.textContent=t;e.className='msg '+k;e.classList.toggle('hide',!t)}
function pt(t=''){let l=t.toLowerCase();if(l.includes('invalid login'))return'E-mail ou senha incorretos.';if(l.includes('email not confirmed'))return'Confirme seu e-mail antes de entrar.';if(l.includes('already'))return'Este e-mail já possui uma conta. Use Entrar.';if(l.includes('file_too_large'))return'O arquivo passa de 10 MB.';return t||'Não foi possível concluir agora.'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function call(n,b){let r=await sb.functions.invoke(n,{body:b});if(r.error)throw new Error(r.error.message);return r.data}
document.querySelectorAll('[data-eye]').forEach(b=>b.onclick=()=>{let i=$(b.dataset.eye),show=i.type==='password';i.type=show?'text':'password';b.textContent=show?'🙈':'👁️'});
function setMode(m){mode=m;let s=m==='signup';$('loginMode').classList.toggle('on',!s);$('signupMode').classList.toggle('on',s);$('signupBox').classList.toggle('hide',!s);$('authTitle').textContent=s?'Criar minha conta':'Entrar na minha conta';$('authGo').textContent=s?'Criar minha conta':'Entrar';check();msg('authMsg','')}
function check(){if(mode!=='signup'){return $('authGo').disabled=false}let a=$('password').value,b=$('password2').value,ok=a.length>=8&&a===b&&$('email').value.trim();$('rules').textContent=(a.length>=8?'✓':'○')+' Pelo menos 8 caracteres · '+(a&&a===b?'✓':'○')+' As duas senhas precisam ser iguais';$('authGo').disabled=!ok;return ok}
$('loginMode').onclick=()=>setMode('login');$('signupMode').onclick=()=>setMode('signup');['email','password','password2'].forEach(i=>$(i).addEventListener('input',check));
$('authGo').onclick=async()=>{let email=$('email').value.trim(),password=$('password').value;msg('authMsg','');if(!email)return msg('authMsg','Informe seu e-mail.','warn');if(mode==='signup'){if(!check())return msg('authMsg','Confira a senha e a confirmação.','warn');let r=await sb.auth.signUp({email,password,options:{emailRedirectTo:APP+'?email-confirmado=1'}});return r.error?msg('authMsg',pt(r.error.message),'bad'):msg('authMsg',r.data.session?'Conta criada e conectada.':'Conta criada. Confirme o e-mail e depois volte ao Career 360.','ok')}if(!password)return msg('authMsg','Informe sua senha.','warn');let r=await sb.auth.signInWithPassword({email,password});if(r.error)msg('authMsg',pt(r.error.message),'bad')};$('logout').onclick=()=>sb.auth.signOut();
const labels=['Sobre você','Seu objetivo','Proteção','Atribuições','Currículo'];
function val(id){return($(id)?.value||'').trim()}
function selectedSkills(){return [...document.querySelectorAll('.skillOpt:checked')].map(x=>x.value).concat(csv(val('obOtherSkills'))).filter(Boolean)}
function save(){try{sessionStorage.setItem('c360_ob',JSON.stringify({step:S.step,name:val('obName'),role:val('obRole'),city:val('obCity'),uf:val('obUf'),targets:val('obTargets'),loc:val('obLoc'),floor:val('obFloor'),salary:val('obSalary'),working:$('obWorking').checked,employer:val('obEmployer'),protect:$('obProtect').checked,blocks:val('obBlocks'),skills:selectedSkills(),other:val('obOtherSkills')}))}catch{}}
function skillCatalog(role=''){let r=role.toLowerCase(),out=[];const add=a=>a.forEach(x=>{if(!out.includes(x))out.push(x)});if(/categoria|compr|buyer|suprimento/.test(r))add(['Gestão de categorias','Negociação com fornecedores','Gestão de margem','Estratégia de sortimento','Compras estratégicas','Planejamento de demanda','Análise de mercado','Gestão de fornecedores','Pricing','Gestão de orçamento']);else if(/comercial|venda|sales|negócio/.test(r))add(['Gestão comercial','Negociação','Planejamento comercial','Gestão por indicadores','Desenvolvimento de negócios','Liderança de equipes','Gestão de carteira','Pricing','Gestão de metas','Relacionamento com clientes']);else if(/diretor|head|superintendente/.test(r))add(['Liderança executiva','Planejamento estratégico','Gestão de P&L','Gestão de equipes','Governança','Tomada de decisão','Gestão de stakeholders','Transformação organizacional','Gestão de orçamento','Desenvolvimento de lideranças']);else add(['Liderança de pessoas','Gestão de equipes','Gestão por indicadores','Planejamento','Negociação','Gestão de projetos','Tomada de decisão','Desenvolvimento de pessoas','Comunicação','Gestão de orçamento']);return out.slice(0,10)}
function renderSkills(){let cat=skillCatalog(val('obRole')||S.profile?.current_role_title||''),cur=new Set([...S.skills,...S.skillSelected]);$('skillBox').innerHTML=cat.map(x=>'<label class="checkitem"><input class="skillOpt" type="checkbox" value="'+esc(x)+'" '+(cur.has(x)?'checked':'')+'><span>'+esc(x)+'</span></label>').join('');document.querySelectorAll('.skillOpt').forEach(x=>x.addEventListener('change',save))}
$('selectAllSkills').onclick=()=>{document.querySelectorAll('.skillOpt').forEach(x=>x.checked=true);save()};$('clearSkills').onclick=()=>{document.querySelectorAll('.skillOpt').forEach(x=>x.checked=false);$('obOtherSkills').value='';save()};$('obRole').addEventListener('input',()=>{renderSkills();save()});
function restore(){let p=S.profile||{},q=S.prefs||{},set=(id,v)=>{if(v!==null&&v!==undefined&&v!=='')$(id).value=v};set('obName',p.display_name);set('obRole',p.current_role_title);set('obCity',p.city);set('obUf',p.state_code);set('obTargets',(q.target_roles||[]).join(', '));set('obLoc',(q.preferred_locations||[]).join(', '));set('obFloor',q.salary_floor_brl);set('obSalary',q.salary_target_brl);$('obWorking').checked=!!p.current_employment_confirmed;set('obEmployer',p.current_employer);set('obBlocks',S.blocks.filter(x=>x.block_reason!=='current_employer').map(x=>x.employer_name).join(', '));S.skillSelected=new Set(S.skills);try{let d=JSON.parse(sessionStorage.getItem('c360_ob')||'null');if(d){S.step=Math.min(5,Math.max(1,d.step||1));[['obName','name'],['obRole','role'],['obCity','city'],['obUf','uf'],['obTargets','targets'],['obLoc','loc'],['obFloor','floor'],['obSalary','salary'],['obEmployer','employer'],['obBlocks','blocks'],['obOtherSkills','other']].forEach(([a,b])=>{if(d[b])$(a).value=d[b]});$('obWorking').checked=!!d.working;$('obProtect').checked=d.protect!==false;S.skillSelected=new Set(d.skills||S.skills)}}catch{}renderSkills();renderStep()}
function renderStep(){for(let i=1;i<=5;i++)$('s'+i).classList.toggle('on',i===S.step);$('bar').style.width=(S.step*20)+'%';$('ptext').textContent='Passo '+S.step+' de 5';$('plabel').textContent=labels[S.step-1];$('back').classList.toggle('hide',S.step===1);$('next').textContent=S.step===5?'Ativar meu agente':'Próximo';$('later').textContent=S.step===5?'Fazer depois':'Continuar depois';if(S.step===4)renderSkills();if(S.step===5)$('summary').innerHTML='<div><span>Você</span><strong>'+esc(val('obName')||'—')+'</strong></div><div><span>Busca</span><strong>'+esc(val('obTargets')||'—')+'</strong></div><div><span>Local</span><strong>'+esc(val('obLoc')||'—')+'</strong></div>';save()}
function valid(){if(S.step===1&&val('obName').split(/\s+/).length<2){alert('Informe seu nome completo para continuar.');return false}if(S.step===2&&!val('obTargets')){alert('Informe pelo menos um cargo que você procura.');return false}return true}
function onboardingPayload(draftId=S.draft){return{draft_id:draftId||null,profile:{display_name:val('obName'),current_role_title:val('obRole'),current_employer:val('obEmployer'),current_employment_confirmed:$('obWorking').checked,city:val('obCity'),state_code:val('obUf')},preferences:{target_roles:csv(val('obTargets')),preferred_locations:csv(val('obLoc')),work_models:csv(val('obLoc')).some(x=>x.toLowerCase().includes('remoto'))?['remote']:[],salary_floor_brl:val('obFloor')?Number(val('obFloor')):null,salary_target_brl:val('obSalary')?Number(val('obSalary')):null,preferred_sectors:[],autonomy_level:'one_action'},skills:selectedSkills(),protect_current_employer:$('obProtect').checked,employer_blocks:csv(val('obBlocks')).map(employer_name=>({employer_name,block_reason:'user_requested'}))}}
async function finish(){try{$('next').disabled=true;$('next').textContent='Ativando...';await call(F.con,onboardingPayload());sessionStorage.removeItem('c360_ob');S.draft=null;S.parsed=null;await window.C.refresh()}catch(e){alert(pt(e.message))}finally{$('next').disabled=false;$('next').textContent='Ativar meu agente'}}
$('next').onclick=async()=>{if(!valid())return;if(S.step<5){S.step++;renderStep()}else await finish()};$('back').onclick=()=>{if(S.step>1){S.step--;renderStep()}};$('later').onclick=()=>{save();$('onboarding').classList.add('hide');$('main').classList.remove('hide');$('startCard').classList.remove('hide');window.C.view('home')};
$('resumeOb').onclick=$('editProfile').onclick=$('homeEdit').onclick=()=>{$('main').classList.add('hide');$('onboarding').classList.remove('hide');renderStep()};document.querySelectorAll('#onboarding input').forEach(x=>x.addEventListener('input',save));
let empTimer;async function empSuggest(){clearTimeout(empTimer);let q=val('obEmployer'),box=$('employerSuggest');if(q.length<2){box.classList.add('hide');return}empTimer=setTimeout(async()=>{let local=[S.profile?.current_employer,...S.blocks.map(x=>x.employer_name)].filter(Boolean),remote=[];try{let r=await call(F.emp,{q});remote=r.items||[]}catch{}let items=[...new Set([...remote,...local].filter(x=>x&&x.toLowerCase().includes(q.toLowerCase())))].slice(0,8);if(!items.length){box.classList.add('hide');return}box.innerHTML=items.map(x=>'<button type="button" class="suggestion" data-name="'+esc(x)+'">'+esc(x)+'</button>').join('');box.classList.remove('hide');box.querySelectorAll('.suggestion').forEach(b=>b.onclick=()=>{$('obEmployer').value=b.dataset.name;box.classList.add('hide');save()})},180)}$('obEmployer').addEventListener('input',empSuggest);document.addEventListener('click',e=>{if(!e.target.closest('.autocomplete'))$('employerSuggest').classList.add('hide')});
function draftInfo(dr){let v=x=>x&&typeof x==='object'&&'value'in x?x.value:x||'',name=v(dr?.name),skills=(dr?.skills_evidence||[]).map(v).filter(Boolean);return{name,skills}}
async function uploadCv(file,msgId,late=false){if(!file)return msg(msgId,'Escolha um PDF ou DOCX.','warn');if(file.size>10485760)return msg(msgId,'Arquivo acima de 10 MB.','bad');try{msg(msgId,'Recebendo e analisando seu currículo com segurança...');let d=new FormData();d.append('file',file,file.name);let a=await call(F.ing,d),b=await call(F.pro,{document_id:a.document_id});S.draft=b.draft_id;S.parsed=b.candidate_profile_draft||{};let dr=draftInfo(S.parsed);if(!val('obName')&&dr.name)$('obName').value=dr.name;if(dr.skills.length)S.skillSelected=new Set([...S.skillSelected,...dr.skills]);renderSkills();msg(msgId,'✅ Currículo recebido e processado com sucesso. Revise e confirme antes de usar os dados.','ok');if(late){$('cvDraftPreview').innerHTML='<strong>O que identificamos para sua revisão</strong>'+(dr.name?'<div class="statusline"><span>Nome</span><b>'+esc(dr.name)+'</b></div>':'')+(dr.skills.length?'<div><span class="muted">Competências encontradas</span><div class="tags">'+dr.skills.map(x=>'<span class="tag">'+esc(x)+'</span>').join('')+'</div></div>':'<p class="muted">O parser não encontrou competências com confiança suficiente. Seus dados atuais serão preservados.</p>');$('cvDraftPreview').classList.remove('hide');$('confirmCv').classList.remove('hide')}save()}catch(e){msg(msgId,pt(e.message),'bad')}}
$('obCvGo').onclick=()=>uploadCv($('obCv').files[0],'obCvMsg',false);$('lateCvGo').onclick=()=>uploadCv($('lateCv').files[0],'lateCvMsg',true);
function currentProfilePayload(draftId){let p=S.profile||{},q=S.prefs||{},parsed=draftInfo(S.parsed),skills=[...new Set([...S.skills,...parsed.skills])];return{draft_id:draftId,profile:{display_name:p.display_name,current_role_title:p.current_role_title,current_employer:p.current_employer,current_employment_confirmed:!!p.current_employment_confirmed,city:p.city,state_code:p.state_code},preferences:{target_roles:q.target_roles||[],preferred_locations:q.preferred_locations||[],work_models:q.work_models||[],salary_floor_brl:q.salary_floor_brl,salary_target_brl:q.salary_target_brl,preferred_sectors:q.preferred_sectors||[],autonomy_level:q.autonomy_level||'one_action'},skills,protect_current_employer:true,employer_blocks:S.blocks.filter(x=>x.block_reason!=='current_employer').map(x=>({employer_name:x.employer_name,block_reason:x.block_reason||'user_requested'}))}}
$('confirmCv').onclick=async()=>{if(!S.draft)return;try{$('confirmCv').disabled=true;$('confirmCv').textContent='Confirmando...';await call(F.con,currentProfilePayload(S.draft));msg('lateCvMsg','✅ Currículo confirmado. Os dados confirmados foram mantidos e o arquivo bruto foi removido com segurança.','ok');S.draft=null;S.parsed=null;$('cvDraftPreview').classList.add('hide');$('confirmCv').classList.add('hide');await window.C.refresh()}catch(e){msg('lateCvMsg',pt(e.message),'bad')}finally{$('confirmCv').disabled=false;$('confirmCv').textContent='Confirmar atualização do currículo'}};
window.C={sb,$,csv,F,S,msg,pt,esc,call,setMode,check,val,selectedSkills,save,skillCatalog,renderSkills,restore,renderStep,valid,onboardingPayload,finish,empSuggest,draftInfo,uploadCv,currentProfilePayload};