const {sb,$,msg,pt}=window.C;
const SUPA='https://nxjdnzdxclszqyqrkwdk.supabase.co';
const KEY='sb_publishable_BCa63l0nMBLzOOHLZPpxfg_Ep2CqYdU';
const arr=v=>Array.isArray(v)?v:[];
function wrap(doc,text,x,y,width,lineHeight=6){const lines=doc.splitTextToSize(String(text||''),width);doc.text(lines,x,y);return y+lines.length*lineHeight}
async function latestProfile(){const s=(await sb.auth.getSession()).data.session;if(!s)throw new Error('AUTH_REQUIRED');const{data,error}=await sb.from('career_professional_profile_versions').select('profile_json').eq('user_id',s.user.id).order('version',{ascending:false}).limit(1).maybeSingle();if(error||!data?.profile_json)throw new Error('PROFILE_NOT_READY');return data.profile_json}
async function signedPhoto(){const s=(await sb.auth.getSession()).data.session;if(!s)return null;const r=await fetch(`${SUPA}/functions/v1/career-profile-photo`,{headers:{Authorization:`Bearer ${s.access_token}`,apikey:KEY}});if(!r.ok)return null;const d=await r.json();return d?.photo?.url||null}
async function imageData(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('PHOTO_FETCH_FAILED');const b=await r.blob();return await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve({data:String(fr.result),format:b.type.includes('png')?'PNG':b.type.includes('webp')?'WEBP':'JPEG'});fr.onerror=reject;fr.readAsDataURL(b)})}
async function downloadCvV8(){try{msg('professionalMsg','Gerando seu PDF no dispositivo...','');const p=await latestProfile();const{jsPDF}=await import('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/+esm');const doc=new jsPDF({unit:'mm',format:'a4'});const includePhoto=Boolean($('cvIncludePhoto')?.checked);let photo=null;if(includePhoto){const u=await signedPhoto();if(u){try{photo=await imageData(u)}catch{photo=null}}}let y=20;const textWidth=photo?132:174;doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text(p.name||'Currículo',18,y,{maxWidth:textWidth});if(photo){try{doc.addImage(photo.data,photo.format,160,14,30,30)}catch{photo=null}}y+=8;doc.setFontSize(11);doc.setFont('helvetica','normal');if(p.headline){const lines=doc.splitTextToSize(p.headline,textWidth);doc.text(lines,18,y);y+=Math.max(10,lines.length*5+2)}if(p.location){doc.text(p.location,18,y);y+=9}if(photo&&y<47)y=47;doc.setDrawColor(220);doc.line(18,y,192,y);y+=8;const title=t=>{if(y>270){doc.addPage();y=20}doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text(t,18,y);y+=6;doc.setFont('helvetica','normal');doc.setFontSize(10)};title('Resumo profissional');y=wrap(doc,p.professional_summary,18,y,174,5)+4;if(arr(p.skills).length){title('Competências');y=wrap(doc,arr(p.skills).join(' • '),18,y,174,5)+4}for(const[t,items]of[['Experiência',arr(p.experience)],['Formação',arr(p.education)],['Idiomas',arr(p.languages)],['Cursos e certificações',arr(p.certifications)]]){if(!items.length)continue;title(t);for(const item of items){if(y>275){doc.addPage();y=20}y=wrap(doc,'• '+item,20,y,170,5)+2}y+=2}doc.setFontSize(8);doc.setTextColor(110);doc.text('Currículo Inteligente LSI Career 360 · gerado a partir de dados confirmados pelo usuário',18,289);doc.save(`Curriculo_${String(p.name||'Career360').replace(/[^a-zA-Z0-9_-]+/g,'_')}.pdf`);msg('professionalMsg',photo?'✅ PDF gerado com a foto que você escolheu incluir.':'✅ PDF gerado no seu dispositivo.','ok')}catch(e){msg('professionalMsg',pt(e.message||'Não consegui gerar o PDF agora.'),'bad')}}
if($('downloadCv'))$('downloadCv').onclick=downloadCvV8;