import './app-a.js';
import './app-c.js';
const {sb,$,csv,F,S,msg,pt,esc,call,setMode,restore}=window.C;
function view(v){document.querySelectorAll('.v').forEach(x=>x.classList.toggle('on',x.id===v));document.querySelectorAll('[data-v]').forEach(x=>{x.classList.toggle('on',x.dataset.v===v);x.classList.toggle('sec',x.dataset.v!==v)});if(v==='opps')loadOpps();if(v==='master')loadMaster()}document.querySelectorAll('[data-v]').forEach(x=>x.onclick=()=>view(x.dataset.v));
window.C.view=view;
sb.auth.onAuthStateChange(async(_,s)=>{S.session=s;$('auth').classList.toggle('hide',!!s);$('app').classList.toggle('hide',!s);if(s)await refresh()});
async function refresh(){let uid=S.session.user.id,[r,p,pr,b,f,d,dr]=await Promise.all([sb.from('career_user_roles').select('role').eq('user_id',uid).maybeSingle(),sb.from('career_profiles').select('*').eq('user_id',uid).maybeSingle(),sb.from('career_preferences').select('*').eq('user_id',uid).maybeSingle(),sb.from('career_employer_blocks').select('employer_name,block_reason').eq('user_id',uid).eq('active',true),sb.from('career_confirmed_facts').select('fact_type,fact_value').eq('user_id',uid).eq('fact_type','skill').is('superseded_at',null),sb.from('career_documents').select('id,original_filename_display,detected_type,file_status,parser_version,created_at,deleted_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(5),sb.from('career_profile_drafts').select('id,document_id,status,draft_json,parser_version,created_at,confirmed_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(1).maybeSingle()]);S.role=r.data?.role||'candidate';S.profile=p.data;S.prefs=pr.data;S.blocks=b.data||[];S.skills=(f.data||[]).map(x=>x.fact_value?.name).filter(Boolean);S.docs=d.data||[];S.cvDraft=dr.data||null;$('role').textContent=S.role==='master'?'Usuário Mestre':'Candidato';$('masterTab').classList.toggle('hide',S.role!=='master');if(S.profile?.display_name)$('hello').textContent='Olá, '+S.profile.display_name.trim().split(/\s+/)[0]+' 👋';restore();let ready=S.profile?.onboarding_status==='agent_ready';$('onboarding').classList.toggle('hide',ready);$('main').classList.toggle('hide',!ready);$('startCard').classList.toggle('hide',ready);renderProfile();renderCvStatus();await loadOpps()}
window.C.refresh=refresh;
function profileCompleteness(){let p=S.profile||{},q=S.prefs||{},checks=[!!p.display_name,!!p.current_role_title,(q.target_roles||[]).length>0,(q.preferred_locations||[]).length>0,S.skills.length>0,S.blocks.length>0];return Math.round(checks.filter(Boolean).length/checks.length*100)}
function renderProfile(){let p=S.profile||{},q=S.prefs||{},pct=profileCompleteness();$('profilePct').textContent=pct+'%';$('profileBar').style.width=pct+'%';$('homeSummary').innerHTML='<div class="statusline"><span>Nome completo</span><b>'+esc(p.display_name||'Pendente')+'</b></div><div class="statusline"><span>Cargo atual</span><b>'+esc(p.current_role_title||'Pendente')+'</b></div><div class="statusline"><span>Objetivos</span><b>'+esc((q.target_roles||[]).join(', ')||'Pendente')+'</b></div><div class="statusline"><span>Local</span><b>'+esc((q.preferred_locations||[]).join(', ')||'Pendente')+'</b></div><div class="statusline"><span>Competências confirmadas</span><b>'+S.skills.length+'</b></div><div class="statusline"><span>Proteções ativas</span><b>'+S.blocks.length+'</b></div><div class="statusline"><span>Currículo</span><b>'+(S.docs.length?'Incluído':'Ainda não incluído · opcional')+'</b></div>';$('profileView').innerHTML='<div class="profileline"><strong>'+esc(p.display_name||'Seu nome')+'</strong><br><span class="muted">'+esc(p.current_role_title||'Cargo ainda não informado')+'</span></div><div class="profileline"><span class="muted">Objetivos</span><br>'+esc((q.target_roles||[]).join(', ')||'Não definidos')+'</div><div class="profileline"><span class="muted">Locais</span><br>'+esc((q.preferred_locations||[]).join(', ')||'Não definidos')+'</div><div class="profileline"><span class="muted">Competências</span><div class="tags">'+(S.skills.length?S.skills.map(x=>'<span class="tag">'+esc(x)+'</span>').join(''):'<span class="muted">Nenhuma confirmada</span>')+'</div></div><div class="profileline"><span class="muted">Proteções ativas</span><br>'+S.blocks.length+'</div>'}
function evidenceValue(v){return v&&typeof v==='object'&&'value'in v?v.value:v}
function listEvidence(items,max=8){return (Array.isArray(items)?items:[]).map(evidenceValue).filter(Boolean).slice(0,max)}
function renderDraftData(){let dr=S.cvDraft?.draft_json;if(!dr)return'';let summary=evidenceValue(dr.summary),exp=listEvidence(dr.experience_evidence,12),edu=listEvidence(dr.education_evidence,8),sk=listEvidence(dr.skills_evidence,12),lang=listEvidence(dr.languages_evidence,8),cert=listEvidence(dr.certifications_evidence,8);let section=(title,items)=>items.length?'<div class="cvsection"><strong>'+title+'</strong><ul>'+items.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></div>':'';return '<details class="cvdetails"><summary>Ver dados extraídos do currículo</summary><p class="muted">Mostramos os dados estruturados que o Career 360 extraiu. O arquivo bruto não precisa permanecer armazenado depois da confirmação.</p>'+(summary?'<div class="cvsection"><strong>Resumo</strong><p>'+esc(summary)+'</p></div>':'')+section('Experiência',exp)+section('Formação',edu)+section('Competências encontradas',sk)+section('Idiomas',lang)+section('Cursos e certificações',cert)+'</details>'}
function renderCvStatus(){let d=S.docs[0],box=$('cvStatusBox');if(!d){box.innerHTML='<div class="cvstate">📄 Nenhum currículo confirmado no sistema</div><p class="muted" style="margin-bottom:0">Se você tentou enviar antes e não recebeu confirmação, o envio não foi concluído. Envie novamente: agora o fluxo informa claramente sucesso ou falha.</p>';return}let when=new Date(d.created_at).toLocaleString('pt-BR'),state=d.file_status==='deleted'?'Processado · arquivo bruto removido com segurança':d.file_status==='parsed'?'Processado e aguardando confirmação':d.file_status==='rejected'?'Não aceito pelo validador':'Recebido com segurança';box.innerHTML='<div class="cvstate">✅ '+esc(state)+'</div><div class="statusline"><span>Arquivo</span><b>'+esc(d.original_filename_display)+'</b></div><div class="statusline"><span>Recebido em</span><b>'+esc(when)+'</b></div><p class="muted">Por segurança, o Career 360 não precisa manter o arquivo bruto depois da confirmação. Você pode revisar os dados extraídos e trocar o currículo quando quiser.</p>'+renderDraftData()}
function home(){let q=S.opps.filter(x=>['QUALIFIED','QUALIFIED_SALARY_CONFIRM'].includes(x.classification)).length;$('m1').textContent=S.opps.length;$('m2').textContent=q;$('m3').textContent=S.blocks.length;$('m4').textContent=0;let cv=!!S.docs.length;if(S.profile?.onboarding_status!=='agent_ready')$('nextText').textContent='Termine o passo a passo para ativar seu agente.';else if(!cv)$('nextText').textContent='Seu perfil básico está ativo. Inclua seu currículo para enriquecer os dados; você não precisa cadastrar vagas manualmente.';else if(!S.opps.length)$('nextText').textContent='Seu perfil está preparado. A pesquisa automática externa ainda precisa ser conectada ao Master Pilot; o Career 360 não vai transferir esse trabalho para você.';else $('nextText').textContent='Seu radar já tem oportunidades. Abra a aba Oportunidades para revisar as melhores.'}
$('oppForm').onsubmit=async e=>{e.preventDefault();try{let r=await call(F.add,{employer_name:$('oe').value,title:$('ot').value,work_model:$('om').value,salary_evidence_class:$('sc').value,salary_max:$('smax').value?Number($('smax').value):null,required_skills:csv($('osk').value)});msg('oppMsg','Teste concluído: '+(r.match?.classification||'criada'),'ok');await loadOpps()}catch(e){msg('oppMsg',pt(e.message),'bad')}};
async function loadOpps(){if(!S.session)return;try{let r=await call(F.list,{limit:50});S.opps=r.items||[];$('oppList').innerHTML='<h2>Seu radar</h2>'+(S.opps.length?S.opps.map(x=>'<div class="opp"><span class="score">'+Math.round(x.score||0)+'%</span> · <strong>'+esc(x.opportunity?.title||'Oportunidade')+'</strong><br><span class="muted">'+esc(x.opportunity?.employer_name||'Empresa')+' · '+esc(x.classification)+'</span></div>').join(''):'<div class="emptyradar"><strong>Nenhuma oportunidade qualificada ainda.</strong><p class="muted">Você não precisa cadastrar vagas. Quando a pesquisa automática estiver conectada, o agente fará isso por você.</p></div>');home()}catch{S.opps=[];home()}}
$('ask').onclick=async()=>{let t=$('question').value.trim();if(!t)return;$('chat').innerHTML+='<div class="bubble me">'+esc(t)+'</div>';$('question').value='';try{let r=await call(F.ag,{message:t});$('chat').innerHTML+='<div class="bubble ai">'+esc(r.answer||'')+'</div>'}catch(e){$('chat').innerHTML+='<div class="bubble ai">'+esc(pt(e.message))+'</div>'}};
$('solve').onclick=async()=>{try{let r=await call(F.sup,{description:$('problem').value});msg('supportMsg',r.resolution,r.status==='resolved'?'ok':'warn')}catch(e){msg('supportMsg',pt(e.message),'bad')}};
async function loadMaster(){if(S.role!=='master')return;try{let r=await call(F.mas,{}),g=r.aggregates||{};$('masterGrid').innerHTML=Object.entries(g).map(([k,v])=>'<div class="metric"><span>'+esc(k)+'</span><strong>'+esc(v)+'</strong></div>').join('');$('gates').textContent=JSON.stringify(r.gates,null,2)}catch(e){$('gates').textContent=pt(e.message)}}
setMode('login');if(new URLSearchParams(location.search).get('email-confirmado')==='1')msg('authMsg','E-mail confirmado. Agora entre com sua senha.','ok');let sess=(await sb.auth.getSession()).data.session;if(sess){S.session=sess;$('auth').classList.add('hide');$('app').classList.remove('hide');await refresh()}