const {sb,$,esc}=window.C;
const SUPA='https://nxjdnzdxclszqyqrkwdk.supabase.co';
const KEY='sb_publishable_BCa63l0nMBLzOOHLZPpxfg_Ep2CqYdU';
const H={profile:null,versionId:null};
function style(){if($('v11style'))return;const s=document.createElement('style');s.id='v11style';s.textContent=`
.my-about-wrap{margin-top:4px}.my-about.clamped{display:-webkit-box;-webkit-line-clamp:4;-webkit-box-orient:vertical;overflow:hidden}.my-more{border:0;background:transparent;color:#6547f5;font-weight:850;padding:8px 0;cursor:pointer}.my-highlights{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:18px}.my-highlight{padding:13px;border:1px solid #ebe8ff;border-radius:15px;background:linear-gradient(180deg,#fbfaff,#f7f5ff);font-size:12px;line-height:1.45;color:#344054}.my-highlight b{display:block;color:#5637e6;font-size:11px;text-transform:uppercase;letter-spacing:.04em;margin-bottom:5px}.my-compact-section{padding-top:16px;margin-top:16px;border-top:1px solid #edf0f5}.my-compact-section h3{font-size:16px;margin:0 0 9px}.my-compact-list{display:grid;gap:8px}.my-compact-item{font-size:13px;line-height:1.5;color:#475467;padding-left:14px;position:relative}.my-compact-item:before{content:'•';position:absolute;left:0;color:#6947f6;font-weight:900}.profile-v11-strip{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin:14px 0}.profile-v11-box{border:1px solid #e9e7f5;border-radius:14px;padding:12px;background:#faf9ff}.profile-v11-box strong{display:block;font-size:13px;margin-bottom:7px}.profile-v11-box ul{margin:0;padding-left:18px;color:#475467;font-size:12px;line-height:1.5}.v11-note{font-size:11px;color:#667085;margin-top:8px}.profile-summary-v8.v11-clamped{display:-webkit-box;-webkit-line-clamp:6;-webkit-box-orient:vertical;overflow:hidden}.v11-cv-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.v11-cv-chip{font-size:11px;font-weight:850;padding:6px 9px;border-radius:999px;background:#ecfdf3;color:#067647}@media(max-width:720px){.my-highlights{grid-template-columns:1fr}.profile-v11-strip{grid-template-columns:1fr}.my-highlight:nth-child(n+3){display:none}}
`;document.head.appendChild(s)}
const arr=v=>Array.isArray(v)?v.filter(Boolean):[];
const clean=(v,max=260)=>String(v||'').replace(/\s+/g,' ').trim().slice(0,max);
function compact(items,max=3){return arr(items).map(x=>clean(x,260)).filter(Boolean).slice(0,max)}
function enhanceMyPage(){const card=$('myPageCard');if(!card)return;const p=H.profile||{};const about=card.querySelector('.my-about');if(about&&!about.closest('.my-about-wrap')){const w=document.createElement('div');w.className='my-about-wrap';about.parentNode.insertBefore(w,about);w.appendChild(about);about.classList.add('clamped');if((about.textContent||'').length>320){const b=document.createElement('button');b.type='button';b.className='my-more';b.textContent='Ver mais';b.onclick=()=>{const open=!about.classList.contains('clamped');about.classList.toggle('clamped',open);b.textContent=open?'Ver mais':'Ver menos'};w.appendChild(b)}}
if(card.querySelector('.my-highlights'))return;const main=card.querySelector('.my-main');if(!main)return;const highlights=compact(p.highlights,3);const leadership=compact(p.leadership,2);const exp=compact(p.experience,3);const edu=compact(p.education,2);const existingSections=[...main.querySelectorAll('.my-section')];existingSections.forEach(x=>x.remove());if(highlights.length){const d=document.createElement('div');d.className='my-highlights';d.innerHTML=highlights.map((x,i)=>`<div class="my-highlight"><b>${i===0?'Destaque profissional':'Impacto'}</b>${esc(x)}</div>`).join('');main.appendChild(d)}
const sec=(title,items)=>{if(!items.length)return;const d=document.createElement('div');d.className='my-compact-section';d.innerHTML=`<h3>${esc(title)}</h3><div class="my-compact-list">${items.map(x=>`<div class="my-compact-item">${esc(x)}</div>`).join('')}</div>`;main.appendChild(d)};sec('Liderança e escopo',leadership);sec('Experiência',exp);sec('Formação',edu)}
function enhanceProfessional(){const box=$('professionalPreview');if(!box||!H.profile)return;const p=H.profile;const card=box.querySelector('.profile-card-v8');if(!card)return;const sum=card.querySelector('.profile-summary-v8');if(sum)sum.classList.add('v11-clamped');let strip=card.querySelector('.profile-v11-strip');if(strip)return;const highlights=compact(p.highlights,4),leadership=compact(p.leadership,3);if(!highlights.length&&!leadership.length)return;strip=document.createElement('div');strip.className='profile-v11-strip';strip.innerHTML=`${highlights.length?`<div class="profile-v11-box"><strong>✨ Destaques</strong><ul>${highlights.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${leadership.length?`<div class="profile-v11-box"><strong>👥 Liderança e escopo</strong><ul>${leadership.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}`;const tags=card.querySelector('.tags');if(tags)tags.parentNode.insertBefore(strip,tags);else card.insertBefore(strip,card.firstChild.nextSibling);const note=document.createElement('div');note.className='v11-note';note.textContent='Perfil organizado a partir de informações confirmadas; nenhuma informação nova é criada automaticamente.';strip.after(note)}
async function load(){const se=(await sb.auth.getSession()).data.session;if(!se)return;const uid=se.user.id;const r=await sb.from('career_professional_profile_versions').select('id,status,profile_json,version').eq('user_id',uid).order('version',{ascending:false}).limit(1).maybeSingle();H.profile=r.data?.profile_json||null;H.versionId=r.data?.id||null;setTimeout(()=>{enhanceMyPage();enhanceProfessional()},180)}
function observe(){const root=$('app');if(!root)return;let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{enhanceMyPage();enhanceProfessional()},100)}).observe(root,{childList:true,subtree:true})}
style();observe();sb.auth.onAuthStateChange((_,s)=>{if(s)setTimeout(load,400)});const se=(await sb.auth.getSession()).data.session;if(se)await load();
