-- Career 360 — O*NET 31.0 lookup layer V1
-- External taxonomy evidence only. It does NOT auto-promote aliases into the curated Role Graph.

create table if not exists public.career_onet_occupations (
  onetsoc_code text primary key,
  title text not null,
  normalized_title text not null,
  description_safe text,
  source_version text not null,
  source_url text not null,
  source_fetched_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.career_onet_job_titles (
  id bigint generated by default as identity primary key,
  onetsoc_code text not null references public.career_onet_occupations(onetsoc_code) on delete cascade,
  occupation_title text not null,
  job_title text not null,
  normalized_job_title text not null,
  short_title text,
  source_codes text,
  source_version text not null,
  source_url text not null,
  source_fetched_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_career_onet_job_titles_code_norm
  on public.career_onet_job_titles(onetsoc_code, normalized_job_title);
create index if not exists idx_career_onet_occupations_norm
  on public.career_onet_occupations(normalized_title);
create index if not exists idx_career_onet_job_titles_norm
  on public.career_onet_job_titles(normalized_job_title);
create index if not exists idx_career_onet_occupations_trgm
  on public.career_onet_occupations using gin(normalized_title gin_trgm_ops);
create index if not exists idx_career_onet_job_titles_trgm
  on public.career_onet_job_titles using gin(normalized_job_title gin_trgm_ops);

alter table public.career_onet_occupations enable row level security;
alter table public.career_onet_job_titles enable row level security;

revoke all on table public.career_onet_occupations from public, anon, authenticated;
revoke all on table public.career_onet_job_titles from public, anon, authenticated;
grant select,insert,update,delete on table public.career_onet_occupations to service_role;
grant select,insert,update,delete on table public.career_onet_job_titles to service_role;
grant usage,select on sequence public.career_onet_job_titles_id_seq to service_role;

comment on table public.career_onet_occupations is
  'Pinned O*NET occupation lookup evidence. Not a canonical Role Graph concept table.';
comment on table public.career_onet_job_titles is
  'Pinned O*NET job-title lookup evidence. Titles do not become Career 360 aliases automatically.';

create or replace function public.career_onet_search(
  p_query text,
  p_limit integer default 12
)
returns table(
  onetsoc_code text,
  occupation_title text,
  job_title text,
  short_title text,
  match_score numeric,
  match_type text,
  source_version text
)
language sql
stable
security definer
set search_path = public, extensions
as $$
  with q as (
    select public.career_normalize_text(coalesce(p_query,'')) n,
           greatest(1, least(coalesce(p_limit,12),50)) lim
  ), exacts as (
    select jt.onetsoc_code,
           jt.occupation_title,
           jt.job_title,
           jt.short_title,
           1.000::numeric match_score,
           'exact_job_title'::text match_type,
           jt.source_version,
           1 ord
    from public.career_onet_job_titles jt,q
    where q.n<>'' and jt.normalized_job_title=q.n
    union all
    select o.onetsoc_code,
           o.title,
           o.title,
           null::text,
           1.000::numeric,
           'exact_occupation_title'::text,
           o.source_version,
           1
    from public.career_onet_occupations o,q
    where q.n<>'' and o.normalized_title=q.n
  ), fuzzy as (
    select jt.onetsoc_code,
           jt.occupation_title,
           jt.job_title,
           jt.short_title,
           round(greatest(similarity(jt.normalized_job_title,q.n), similarity(public.career_normalize_text(jt.occupation_title),q.n))::numeric,3),
           'fuzzy_title'::text,
           jt.source_version,
           2 ord
    from public.career_onet_job_titles jt,q
    where q.n<>''
      and (jt.normalized_job_title % q.n or public.career_normalize_text(jt.occupation_title) % q.n)
      and greatest(similarity(jt.normalized_job_title,q.n), similarity(public.career_normalize_text(jt.occupation_title),q.n)) >= 0.45
  ), combined as (
    select * from exacts
    union all
    select * from fuzzy
  )
  select distinct on(c.onetsoc_code, public.career_normalize_text(c.job_title))
         c.onetsoc_code,c.occupation_title,c.job_title,c.short_title,c.match_score,c.match_type,c.source_version
  from combined c,q
  order by c.onetsoc_code,public.career_normalize_text(c.job_title),c.ord,c.match_score desc
  limit (select lim from q);
$$;

revoke all on function public.career_onet_search(text,integer) from public, anon, authenticated;
grant execute on function public.career_onet_search(text,integer) to service_role;

comment on function public.career_onet_search(text,integer) is
  'Service-only O*NET lookup. Evidence/search layer only; does not mutate the curated Role Graph.';
