import { createClient } from "jsr:@supabase/supabase-js@2.114.0";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-lsi-proactive-secret","Access-Control-Allow-Methods":"POST, OPTIONS"};
function json(status:number,body:Record<string,unknown>){return new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}})}
function n(v:any){return Number(v||0)}
function bodyText(s:any){const p:string[]=[];if(n(s.qualified)>0)p.push(`${s.qualified} nova(s) oportunidade(s) qualificada(s)`);if(n(s.applied)>0)p.push(`${s.applied} candidatura(s) registrada(s)`);if(n(s.replies)>0)p.push(`${s.replies} resposta(s) de recrutador/empresa`);if(n(s.interviews)>0)p.push(`${s.interviews} avanço(s) para entrevista`);if(n(s.action_required)>0)p.push(`${s.action_required} ação(ões) aguardando você`);if(!p.length&&n(s.analyzed)>0)p.push(`${s.analyzed} oportunidade(s) analisada(s); nenhuma atingiu o corte atual`);if(!p.length)p.push("Sem novidades relevantes desde a última atualização; seu agente continua ativo.");return p.join(" · ")}
async function makeDigest(service:any,userId:string,force=false){
  const{data:pref,error:pErr}=await service.from("career_digest_preferences").select("user_id,plan_key,cadence_hours,timezone,in_app_enabled,email_enabled,critical_immediate,last_digest_at,next_digest_at").eq("user_id",userId).maybeSingle();if(pErr||!pref)return{ok:false,error:"DIGEST_PREFERENCE_NOT_FOUND"};
  const now=new Date();if(!force&&pref.next_digest_at&&new Date(pref.next_digest_at)>now)return{ok:true,skipped:true,reason:"NOT_DUE"};
  const end=now.toISOString(),start=pref.last_digest_at||new Date(now.getTime()-n(pref.cadence_hours)*3600000).toISOString();
  const{data:ctl}=await service.from("career_engine_control").select("champion_version").eq("component","matching").maybeSingle();const engine=ctl?.champion_version||"v2.0";
  const[mR,aR,mailR,ledR]=await Promise.all([
    service.from("career_matches").select("classification,updated_at").eq("user_id",userId).eq("engine_version",engine).gt("updated_at",start).lte("updated_at",end),
    service.from("career_applications").select("status,last_activity_at").eq("user_id",userId).gt("last_activity_at",start).lte("last_activity_at",end),
    service.from("career_mail_actions").select("direction,status,critical,requires_human,message_kind,updated_at,created_at").eq("user_id",userId).gte("updated_at",start).lte("updated_at",end),
    service.from("career_activity_ledger").select("event_type,title,summary_safe,importance,occurred_at").eq("user_id",userId).gt("occurred_at",start).lte("occurred_at",end).order("occurred_at",{ascending:false}).limit(20)
  ]);if(mR.error||aR.error||mailR.error||ledR.error)return{ok:false,error:"DIGEST_SOURCE_READ_FAILED"};
  const matches=mR.data||[],apps=aR.data||[],mails=mailR.data||[],ledger=ledR.data||[];
  const summary:any={engine_version:engine,window_start:start,window_end:end,analyzed:matches.filter((x:any)=>x.classification!=="EXPIRED").length,qualified:matches.filter((x:any)=>["QUALIFIED","QUALIFIED_SALARY_CONFIRM"].includes(x.classification)).length,discarded:matches.filter((x:any)=>["BELOW_FIT","BLOCKED_REQUIREMENT"].includes(x.classification)).length,privacy_protected:matches.filter((x:any)=>x.classification==="BLOCKED_PRIVACY").length,applied:apps.filter((x:any)=>x.status==="applied").length,replies:apps.filter((x:any)=>x.status==="recruiter_reply").length+mails.filter((x:any)=>x.direction==="inbound").length,interviews:apps.filter((x:any)=>["interview_pending","interview_confirmed"].includes(x.status)).length,offers:apps.filter((x:any)=>x.status==="offer").length,hires:apps.filter((x:any)=>x.status==="hired").length,action_required:mails.filter((x:any)=>["awaiting_approval","draft_ready"].includes(x.status)||x.requires_human===true).length,critical:mails.filter((x:any)=>x.critical===true).length,recent_activity:ledger.slice(0,5),cadence_hours:pref.cadence_hours,plan_key:pref.plan_key};
  const text=bodyText(summary);const{data:run,error:rErr}=await service.from("career_digest_runs").insert({user_id:userId,window_start:start,window_end:end,cadence_hours:pref.cadence_hours,status:pref.in_app_enabled?"delivered_in_app":"generated",summary_json:summary,delivered_at:pref.in_app_enabled?end:null}).select("id").single();if(rErr||!run)return{ok:false,error:"DIGEST_WRITE_FAILED"};
  if(pref.in_app_enabled)await service.from("career_notifications").insert({user_id:userId,kind:"digest",title:"Atualização do seu Career 360",body:text,source_event_key:`digest:${run.id}`,action_type:"open_digest",action_payload_safe:{digest_run_id:run.id}});
  await service.from("career_activity_ledger").insert({user_id:userId,event_type:"digest_generated",stage:"agent_update",actor:"system",entity_type:"career_digest_runs",entity_id:run.id,title:"Resumo periódico gerado",summary_safe:text,importance:summary.critical>0?"high":"normal",metadata_safe:{cadence_hours:pref.cadence_hours,engine_version:engine}});
  await service.from("career_digest_preferences").update({last_digest_at:end,next_digest_at:new Date(now.getTime()+n(pref.cadence_hours)*3600000).toISOString(),updated_at:end}).eq("user_id",userId);
  return{ok:true,skipped:false,digest_run_id:run.id,summary,text,email_delivery_pending:pref.email_enabled};
}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json(405,{error:"METHOD_NOT_ALLOWED"});const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!anon||!serviceKey)return json(500,{error:"SERVER_CONFIG_ERROR"});const service:any=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});let body:any={};try{body=await req.json()}catch{}const cron=req.headers.get("x-lsi-proactive-secret");if(cron){const{data:valid}=await service.rpc("career_validate_proactive_cron_secret",{p_secret:cron});if(valid!==true)return json(401,{error:"INVALID_CRON_SECRET"});const{data:due,error}=await service.from("career_digest_preferences").select("user_id").eq("in_app_enabled",true).or(`next_digest_at.is.null,next_digest_at.lte.${new Date().toISOString()}`).limit(200);if(error)return json(503,{error:"DUE_USERS_READ_FAILED"});const results:any[]=[];for(const row of due||[])results.push({user_id:row.user_id,...await makeDigest(service,row.user_id,false)});return json(200,{status:"PROACTIVE_DIGEST_CYCLE_COMPLETE",processed:results.length,results})}const h=req.headers.get("Authorization");if(!h?.startsWith("Bearer "))return json(401,{error:"AUTH_REQUIRED"});const uc=createClient(url,anon,{global:{headers:{Authorization:h}},auth:{persistSession:false,autoRefreshToken:false}});const{data:u,error:ue}=await uc.auth.getUser();if(ue||!u.user)return json(401,{error:"INVALID_SESSION"});if(String(body?.action||"generate_now")!=="generate_now")return json(400,{error:"ACTION_NOT_SUPPORTED"});const result=await makeDigest(service,u.user.id,true);return json(result.ok?200:503,result)});