import { createClient } from "jsr:@supabase/supabase-js@2.114.0";

const BUCKET="career-profile-private";
const MAX=5*1024*1024;
const SIGN=3600;
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const json=(status:number,body:any)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const clean=(v:any,max=180)=>typeof v==='string'?v.replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max):'';
const list=(v:any,max=8)=>Array.isArray(v)?v.map(x=>clean(x,120)).filter(Boolean).slice(0,max):[];
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function detect(bytes:Uint8Array){if(bytes.length>=3&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)return{mime:'image/jpeg',ext:'jpg'};if(bytes.length>=8&&bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47)return{mime:'image/png',ext:'png'};if(bytes.length>=12&&String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP')return{mime:'image/webp',ext:'webp'};return null}
const hex=(b:ArrayBuffer)=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function signed(s:any,path?:string|null){if(!path)return null;const{data,error}=await s.storage.from(BUCKET).createSignedUrl(path,SIGN);return error?null:data?.signedUrl||null}
async function ctx(req:Request){const h=req.headers.get('Authorization');if(!h?.startsWith('Bearer '))return{error:json(401,{error:'AUTH_REQUIRED'})};const url=Deno.env.get('SUPABASE_URL'),anon=Deno.env.get('SUPABASE_ANON_KEY'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!anon||!key)return{error:json(500,{error:'SERVER_CONFIG_ERROR'})};const uc=createClient(url,anon,{global:{headers:{Authorization:h}},auth:{persistSession:false,autoRefreshToken:false}});const{data,error}=await uc.auth.getUser();if(error||!data.user)return{error:json(401,{error:'INVALID_SESSION'})};return{user:data.user,service:createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}}
function recommend(role:string,targets:string[]){const t=norm([role,...targets].join(' '));if(/diretor|director|head|vp|vice president|c-level|chief|executiv/.test(t))return{key:'executive',label:'Executivo contemporâneo',reason:'Seu perfil está direcionado a posições de liderança e decisão.',presentation:'retrato executivo contemporâneo, sóbrio, confiante e natural'};if(/comercial|sales|compras|procurement|category|categoria|business|negoci/.test(t))return{key:'corporate',label:'Corporativo natural',reason:'Seu perfil valoriza relacionamento, negociação e gestão.',presentation:'retrato corporativo natural, acessível e confiante'};if(/tech|tecnologia|produto|product|data|dados|engineer|software|design/.test(t))return{key:'modern',label:'Profissional moderno',reason:'Seu perfil está ligado a ambientes modernos de produto, tecnologia ou dados.',presentation:'retrato profissional moderno, limpo e contemporâneo'};if(/criativ|creative|marketing|conteudo|content|arte|brand/.test(t))return{key:'creative',label:'Profissional expressivo',reason:'Seu perfil permite uma apresentação profissional com mais personalidade.',presentation:'retrato profissional expressivo, refinado e contemporâneo'};return{key:'corporate',label:'Corporativo natural',reason:'É a opção mais versátil para uma apresentação profissional.',presentation:'retrato corporativo natural, limpo e confiante'}}
function prompt(style:any,role:string,targets:string[]){return{version:'career-photo-v1',intent:style.presentation,current_role:role||null,target_roles:targets,identity_rules:['preservar identidade facial e características reais','não alterar idade aparente','não alterar gênero ou características físicas','não afinar ou modificar rosto/corpo','não inferir atributos sensíveis'],presentation_rules:['enquadramento profissional de cabeça e ombros','expressão natural e confiante','iluminação suave e uniforme','fundo neutro e discreto compatível com ambiente profissional','aparência fotográfica realista, sem efeito artificial'],matching_usage:false}}
async function state(service:any,userId:string){const[{data:media},{data:prefs},{data:profile},{data:prefCareer},{data:variants}]=await Promise.all([service.from('career_profile_media').select('id,storage_object_path,mime_type,updated_at').eq('user_id',userId).eq('media_type','profile_photo').maybeSingle(),service.from('career_photo_preferences').select('*').eq('user_id',userId).maybeSingle(),service.from('career_profiles').select('current_role_title').eq('user_id',userId).maybeSingle(),service.from('career_preferences').select('target_roles').eq('user_id',userId).maybeSingle(),service.from('career_photo_variants').select('id,style_key,style_reason,generation_mode,provider,status,storage_object_path,mime_type,created_at,ready_at,accepted_at').eq('user_id',userId).order('created_at',{ascending:false}).limit(8)]);const role=clean(profile?.current_role_title),targets=list(prefCareer?.target_roles);const rec=recommend(role,targets);const original=media?{id:media.id,url:await signed(service,media.storage_object_path),mime_type:media.mime_type,updated_at:media.updated_at}:null;const enriched=[];for(const v of variants||[])enriched.push({...v,url:await signed(service,v.storage_object_path)});const active=prefs?.active_variant_id?enriched.find((v:any)=>v.id===prefs.active_variant_id)||null:null;return{original,active_variant:active,variants:enriched,recommendation:rec,career_context:{current_role:role||null,target_roles:targets},prompt:prompt(rec,role,targets),provider_status:{local_polish:true,generative:false,reason:'No generative image provider configured in runtime'}}}

Deno.serve(async(req)=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
  const c:any=await ctx(req); if(c.error)return c.error; const u=c.user,s=c.service;
  if(req.method==='GET')return json(200,{status:'PHOTO_STUDIO_READY',...(await state(s,u.id))});
  if(req.method!=='POST')return json(405,{error:'METHOD_NOT_ALLOWED'});
  const ct=req.headers.get('content-type')||'';
  if(ct.includes('multipart/form-data')){
    let f:FormData; try{f=await req.formData()}catch{return json(400,{error:'INVALID_MULTIPART'})}
    const file=f.get('file'),style=clean(f.get('style_key'),30);
    if(!(file instanceof File))return json(400,{error:'PHOTO_REQUIRED'});
    if(!['executive','corporate','modern','creative'].includes(style))return json(400,{error:'STYLE_INVALID'});
    if(file.size<=0||file.size>MAX)return json(413,{error:'PHOTO_TOO_LARGE'});
    const bytes=new Uint8Array(await file.arrayBuffer()),kind=detect(bytes); if(!kind)return json(415,{error:'PHOTO_TYPE_NOT_ALLOWED'});
    const{data:media}=await s.from('career_profile_media').select('id').eq('user_id',u.id).eq('media_type','profile_photo').maybeSingle(); if(!media)return json(409,{error:'ORIGINAL_PHOTO_REQUIRED'});
    const{data:profile}=await s.from('career_profiles').select('current_role_title').eq('user_id',u.id).maybeSingle();
    const{data:pc}=await s.from('career_preferences').select('target_roles').eq('user_id',u.id).maybeSingle();
    const role=clean(profile?.current_role_title),targets=list(pc?.target_roles),rec=recommend(role,targets);
    const path=`${u.id}/professional/${crypto.randomUUID()}.${kind.ext}`;
    const{error:up}=await s.storage.from(BUCKET).upload(path,bytes,{contentType:kind.mime,cacheControl:'0',upsert:false}); if(up)return json(503,{error:'VARIANT_UPLOAD_FAILED'});
    const sha=hex(await crypto.subtle.digest('SHA-256',bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer));
    const{data:row,error:w}=await s.from('career_photo_variants').insert({user_id:u.id,source_media_id:media.id,style_key:style,style_reason:style===rec.key?rec.reason:'Estilo escolhido pelo usuário.',generation_mode:'local_polish',provider:'browser_local',prompt_version:'career-photo-v1',prompt_safe:prompt({...rec,key:style},role,targets),storage_object_path:path,mime_type:kind.mime,size_bytes:file.size,sha256:sha,status:'ready',ready_at:new Date().toISOString()}).select('id,status,style_key,style_reason,created_at').single();
    if(w||!row){await s.storage.from(BUCKET).remove([path]);return json(503,{error:'VARIANT_WRITE_FAILED'})}
    await s.from('career_audit_events').insert({user_id:u.id,event_type:'professional_photo',entity_type:'career_photo_variants',entity_id:row.id,outcome:'ready',reason_code:'LOCAL_IDENTITY_PRESERVING_POLISH',metadata_safe:{style_key:style,generation_mode:'local_polish'}});
    return json(201,{status:'VARIANT_READY',variant:{...row,url:await signed(s,path)},matching_usage:false});
  }
  let b:any={};try{b=await req.json()}catch{}
  const action=clean(b.action,30);
  if(action==='prepare')return json(200,{status:'PHOTO_STUDIO_PREPARED',...(await state(s,u.id))});
  if(action==='set_style'){const style=clean(b.style_key,30);if(!['auto','executive','corporate','modern','creative'].includes(style))return json(400,{error:'STYLE_INVALID'});await s.from('career_photo_preferences').upsert({user_id:u.id,preferred_style:style,updated_at:new Date().toISOString()},{onConflict:'user_id'});return json(200,{status:'STYLE_SAVED',style_key:style})}
  if(action==='accept'){const id=clean(b.variant_id,80);const{data:v}=await s.from('career_photo_variants').select('id,status').eq('id',id).eq('user_id',u.id).maybeSingle();if(!v||!['ready','accepted'].includes(v.status))return json(404,{error:'VARIANT_NOT_READY'});await s.from('career_photo_variants').update({status:'rejected',rejected_at:new Date().toISOString()}).eq('user_id',u.id).eq('status','accepted').neq('id',id);await s.from('career_photo_variants').update({status:'accepted',accepted_at:new Date().toISOString()}).eq('id',id).eq('user_id',u.id);await s.from('career_photo_preferences').upsert({user_id:u.id,active_variant_id:id,updated_at:new Date().toISOString()},{onConflict:'user_id'});await s.from('career_audit_events').insert({user_id:u.id,event_type:'professional_photo',entity_type:'career_photo_variants',entity_id:id,outcome:'accepted',reason_code:'USER_CONFIRMED',metadata_safe:{}});return json(200,{status:'VARIANT_ACCEPTED',...(await state(s,u.id))})}
  if(action==='reject'){const id=clean(b.variant_id,80);const{data:v}=await s.from('career_photo_variants').select('id,storage_object_path').eq('id',id).eq('user_id',u.id).maybeSingle();if(!v)return json(404,{error:'VARIANT_NOT_FOUND'});if(v.storage_object_path)await s.storage.from(BUCKET).remove([v.storage_object_path]);await s.from('career_photo_variants').update({status:'rejected',storage_object_path:null,rejected_at:new Date().toISOString()}).eq('id',id).eq('user_id',u.id);await s.from('career_photo_preferences').update({active_variant_id:null,updated_at:new Date().toISOString()}).eq('user_id',u.id).eq('active_variant_id',id);return json(200,{status:'VARIANT_REJECTED',...(await state(s,u.id))})}
  if(action==='use_original'){await s.from('career_photo_preferences').upsert({user_id:u.id,active_variant_id:null,updated_at:new Date().toISOString()},{onConflict:'user_id'});return json(200,{status:'ORIGINAL_ACTIVE',...(await state(s,u.id))})}
  return json(400,{error:'ACTION_INVALID'});
});
