const VERSION='brazil-opportunity-radar-rapidapi-r1';
const COMPRAS='https://dadosabertos.compras.gov.br/modulo-contratacoes/1_consultarContratacoes_PNCP_14133';
const PNCP='https://pncp.gov.br/api/consulta/v1/contratacoes/proposta';
const TIMEOUT_MS=5000;

function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function text(v){return String(v??'').trim()}
function clamp(v,min,max,fallback){const n=Number.parseInt(String(v??''),10);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback}
function authorized(req,env){const expected=text(env.RAPIDAPI_PROXY_SECRET),got=text(req.headers.get('x-rapidapi-proxy-secret'));if(!expected||got.length!==expected.length)return false;let diff=0;for(let i=0;i<got.length;i++)diff|=got.charCodeAt(i)^expected.charCodeAt(i);return diff===0}
function rows(p){if(Array.isArray(p))return p;for(const k of ['resultado','resultados','results','data','content'])if(Array.isArray(p?.[k]))return p[k];return []}
function first(r,keys){for(const k of keys){const v=r?.[k];if(v!==undefined&&v!==null&&text(v))return v}return null}
function num(r,keys){for(const k of keys){const n=Number(r?.[k]);if(Number.isFinite(n))return n}return null}
function normalize(r,source){return {id:first(r,['idCompra','numeroControlePNCP','numeroCompra']),object:first(r,['objetoCompra','objeto','descricao','descricaoCompra','informacaoComplementar']),estimatedValueBRL:num(r,['valorTotalEstimado','valorEstimado','valorTotal','valorGlobal']),publishedAt:first(r,['dataPublicacaoPncp','dataPublicacao','dataAtualizacaoPncp']),deadlineAt:first(r,['dataEncerramentoProposta','dataFimProposta','dataAberturaProposta']),uf:first(r,['unidadeOrgaoUfSigla','uf','ufSigla'])||r?.unidadeOrgao?.ufSigla||null,organization:first(r,['orgaoEntidadeRazaoSocial','orgaoRazaoSocial','nomeOrgao'])||r?.orgaoEntidade?.razaoSocial||null,unit:first(r,['unidadeOrgaoNomeUnidade','nomeUnidade'])||r?.unidadeOrgao?.nomeUnidade||null,modality:first(r,['modalidadeNome','nomeModalidade','codigoModalidade'])||r?.modalidadeNome||null,sourceUrl:first(r,['linkSistemaOrigem','linkProcessoEletronico','urlCompra']),source}}
function match(x,q,uf){if(uf&&text(x.uf).toUpperCase()!==uf)return false;if(!q)return true;const hay=`${x.object||''} ${x.organization||''} ${x.unit||''} ${x.modality||''}`.toLowerCase();return q.toLowerCase().split(/\s+/).filter(Boolean).every(t=>hay.includes(t))}
function score(x,q){let s=25;if(x.estimatedValueBRL>0)s+=Math.min(25,Math.log10(x.estimatedValueBRL+1)*5);if(x.deadlineAt)s+=10;if(x.sourceUrl)s+=5;if(x.source.includes('propostas'))s+=8;if(q){const hay=`${x.object||''} ${x.organization||''} ${x.unit||''}`.toLowerCase(),terms=q.toLowerCase().split(/\s+/).filter(Boolean);if(terms.length)s+=(terms.filter(t=>hay.includes(t)).length/terms.length)*35}return Math.round(Math.max(0,Math.min(100,s)))}
async function timedFetch(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{return await fetch(url,{headers:{accept:'application/json'},signal:c.signal,cf:{cacheTtl:900,cacheEverything:true}})}finally{clearTimeout(timer)}}
async function feed(url){const started=Date.now(),limit=clamp(url.searchParams.get('limit'),1,50,25),q=text(url.searchParams.get('q')).slice(0,120),uf=text(url.searchParams.get('uf')).toUpperCase().slice(0,2),today=new Date(),from=new Date(),end=new Date();from.setUTCDate(from.getUTCDate()-90);end.setUTCDate(end.getUTCDate()+45);const iso=d=>d.toISOString().slice(0,10),compact=d=>iso(d).replaceAll('-','');
 const tasks=[];
 for(const m of ['5','6']){const p=new URLSearchParams({pagina:'1',tamanhoPagina:'100',dataPublicacaoPncpInicial:iso(from),dataPublicacaoPncpFinal:iso(today),codigoModalidade:m});if(uf)p.set('unidadeOrgaoUfSigla',uf);tasks.push((async()=>{try{const r=await timedFetch(`${COMPRAS}?${p}`);let a=[];if(r.ok)try{a=rows(await r.json())}catch{}return {provider:'Compras.gov.br',modality:m,status:r.status,timeout:false,rows:a}}catch(e){return {provider:'Compras.gov.br',modality:m,status:0,timeout:e?.name==='AbortError',rows:[]}}})())}
 for(const m of ['5','4']){const p=new URLSearchParams({dataFinal:compact(end),codigoModalidadeContratacao:m,pagina:'1'});if(uf)p.set('uf',uf);tasks.push((async()=>{try{const r=await timedFetch(`${PNCP}?${p}`);let a=[];if(r.ok)try{a=rows(await r.json())}catch{}return {provider:'PNCP propostas abertas',modality:m,status:r.status,timeout:false,rows:a}}catch(e){return {provider:'PNCP propostas abertas',modality:m,status:0,timeout:e?.name==='AbortError',rows:[]}}})())}
 const results=await Promise.all(tasks),all=[],upstream=[],now=Date.now();for(const r of results){upstream.push({provider:r.provider,modality:r.modality,status:r.status,timeout:Boolean(r.timeout)});for(const raw of r.rows.slice(0,100)){const x=normalize(raw,r.provider==='Compras.gov.br'?'Compras.gov.br / PNCP':'PNCP — propostas abertas');if(x.deadlineAt){const d=Date.parse(x.deadlineAt);if(Number.isFinite(d)&&d+86400000<now)continue}all.push(x)}}
 const unique=new Map();for(const x of all){const k=text(x.id)||`${x.object}|${x.organization}|${x.publishedAt}`;if(!unique.has(k))unique.set(k,x)}const opportunities=[...unique.values()].filter(x=>match(x,q,uf)).map(x=>({...x,opportunityScore:score(x,q)})).sort((a,b)=>b.opportunityScore-a.opportunityScore||(b.estimatedValueBRL||0)-(a.estimatedValueBRL||0)).slice(0,limit);
 return {ok:true,version:VERSION,densityVersion:'ranked-source-set-2026-08-31',provider:'PNCP + Compras.gov.br',count:opportunities.length,query:q||null,uf:uf||null,opportunities,upstream,elapsedMs:Date.now()-started,financialOutcomeGuaranteed:false}
}
export default {async fetch(request,env){const url=new URL(request.url);if(request.method==='GET'&&url.pathname==='/health')return json({ok:true,service:'LSI Brazil Opportunity Radar — RapidAPI',version:VERSION,proxySecretConfigured:Boolean(env.RAPIDAPI_PROXY_SECRET),monetizationHandledBy:'rapidapi',piiCollected:false,moneyMovement:false});if(request.method==='GET'&&url.pathname==='/v1/opportunities'){if(!env.RAPIDAPI_PROXY_SECRET)return json({ok:false,error:'rapidapi_proxy_secret_not_configured'},503);if(!authorized(request,env))return json({ok:false,error:'rapidapi_proxy_not_authorized'},401);try{return json(await feed(url))}catch(e){return json({ok:false,error:'upstream_unavailable',detail:text(e?.message||e).slice(0,120)},502)}}return json({ok:false,error:'not_found'},404)}};
