import { createClient } from "jsr:@supabase/supabase-js@2.114.0";
const BUCKET='career-profile-private',MAX=5*1024*1024,SIGNED=3600;
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, DELETE, OPTIONS'};
const j=(s:number,b:any)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const hex=(a:ArrayBuffer)=>[...new Uint8Array(a)].map(b=>b.toString(16).padStart(2,'0')).join('');
function detect(b:Uint8Array){if(b.length>=3&&b[0]===255&&b[1]===216&&b[2]===255)return{mime:'image/jpeg',ext:'jpg'};if(b.length>=8&&b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71)return{mime:'image/png',ext:'png'};if(b.length>=12&&String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP')return{mime:'image/webp',ext:'webp'};return null}
async function auth(req:Request){const h=req.headers.get('Authorization');if(!h?.startsWith('Bearer '))return{error:j(401,{error:'AUTH_REQUIRED'})};const url=Deno.env.get('SUPABASE_URL'),anon=Deno.env.get('SUPABASE_ANON_KEY'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!anon||!key)return{error:j(500,{error:'SERVER_CONFIG_ERROR'})};const u=createClient(url,anon,{global:{headers:{Authorization:h}},auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await u.auth.getUser();if(error||!data.user)return{error:j(401,{error:'INVALID_SESSION'})};return{user:data.user,service:createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}}
async function ensure(s:any){const {data}=await s.storage.getBucket(BUCKET);if(data)return true;return !(await s.storage.createBucket(BUCKET,{public:false,fileSizeLimit:MAX,allowedMimeTypes:['image/jpeg','image/png','image/webp']})).error}
async function sign(s:any,p:string|null){if(!p)return null;const {data,error}=await s.storage.from(BUCKET).createSignedUrl(p,SIGNED);return error?null:data?.signedUrl||null}
async function audit(s:any,uid:string,id:string|null,outcome:string,reason:string,meta:any={}){await s.from('career_audit_events').insert({user_id:uid,event_type:'profile_photo',entity_type:'career_profile_media',entity_id:id,outcome,reason_code:reason,metadata_safe:meta})}
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const c:any=await auth(req);if(c.error)return c.error;const uid=c.user.id,s=c.service;
 if(req.method==='GET'){
  const [m,st]=await Promise.all([s.from('career_profile_media').select('id,storage_object_path,mime_type,size_bytes,created_at,updated_at').eq('user_id',uid).eq('media_type','profile_photo').maybeSingle(),s.from('career_profile_photo_settings').select('selected_kind,selected_variant_id').eq('user_id',uid).maybeSingle()]);
  if(m.error)return j(503,{error:'PHOTO_LOOKUP_FAILED'});if(!m.data)return j(200,{status:'NO_PHOTO',photo:null,original_photo:null});
  const original={...m.data,url:await sign(s,m.data.storage_object_path)},sel=st.data;
  if(sel?.selected_kind==='variant'&&sel.selected_variant_id){const {data:v}=await s.from('career_profile_photo_variants').select('id,storage_object_path,mime_type,size_bytes,created_at,style_key,provider,status').eq('id',sel.selected_variant_id).eq('user_id',uid).eq('status','accepted').maybeSingle();if(v){const url=await sign(s,v.storage_object_path);if(url)return j(200,{status:'PHOTO_READY',photo:{...v,url,updated_at:v.created_at},original_photo:original,selected_kind:'variant',matching_usage:false,identity_disclosure:false})}}
  return j(200,{status:'PHOTO_READY',photo:original,original_photo:original,selected_kind:'original',matching_usage:false,identity_disclosure:false});
 }
 if(req.method==='DELETE'){
  const {data:m}=await s.from('career_profile_media').select('id,storage_object_path').eq('user_id',uid).eq('media_type','profile_photo').maybeSingle();if(!m)return j(200,{status:'NO_PHOTO'});
  const {data:vs}=await s.from('career_profile_photo_variants').select('storage_object_path').eq('user_id',uid);const paths=[m.storage_object_path,...(vs||[]).map((x:any)=>x.storage_object_path).filter(Boolean)];
  await s.from('career_profile_photo_settings').upsert({user_id:uid,selected_kind:'original',selected_variant_id:null,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(paths.length)await s.storage.from(BUCKET).remove(paths);const {error}=await s.from('career_profile_media').delete().eq('id',m.id).eq('user_id',uid);if(error)return j(503,{error:'PHOTO_DELETE_FAILED'});await audit(s,uid,m.id,'deleted','USER_REQUESTED',{});return j(200,{status:'PHOTO_DELETED'});
 }
 if(req.method!=='POST')return j(405,{error:'METHOD_NOT_ALLOWED'});
 const len=Number(req.headers.get('content-length')||'0');if(len&&len>MAX+512000)return j(413,{error:'PHOTO_TOO_LARGE'});let form:FormData;try{form=await req.formData()}catch{return j(400,{error:'INVALID_MULTIPART'})}const f=form.get('file');if(!(f instanceof File))return j(400,{error:'PHOTO_REQUIRED'});if(f.size<=0||f.size>MAX)return j(413,{error:'PHOTO_TOO_LARGE',max_bytes:MAX});const b=new Uint8Array(await f.arrayBuffer()),k=detect(b);if(!k)return j(415,{error:'PHOTO_TYPE_NOT_ALLOWED'});if(!(await ensure(s)))return j(503,{error:'PHOTO_BUCKET_UNAVAILABLE'});
 const sha=hex(await crypto.subtle.digest('SHA-256',b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength) as ArrayBuffer)),path=`${uid}/${crypto.randomUUID()}.${k.ext}`;const {error:up}=await s.storage.from(BUCKET).upload(path,b,{contentType:k.mime,cacheControl:'0',upsert:false});if(up)return j(503,{error:'PHOTO_UPLOAD_FAILED'});
 const {data:old}=await s.from('career_profile_media').select('id,storage_object_path').eq('user_id',uid).eq('media_type','profile_photo').maybeSingle(),now=new Date().toISOString();const {data:row,error}=await s.from('career_profile_media').upsert({user_id:uid,media_type:'profile_photo',storage_object_path:path,mime_type:k.mime,size_bytes:f.size,sha256:sha,updated_at:now},{onConflict:'user_id,media_type'}).select('id,updated_at').single();if(error||!row){await s.storage.from(BUCKET).remove([path]);return j(503,{error:'PHOTO_METADATA_WRITE_FAILED'})}
 const {data:vs}=await s.from('career_profile_photo_variants').select('storage_object_path').eq('user_id',uid).neq('status','rejected');const stale=(vs||[]).map((x:any)=>x.storage_object_path).filter(Boolean);if(stale.length)await s.storage.from(BUCKET).remove(stale);await s.from('career_profile_photo_variants').update({status:'superseded',storage_object_path:null,decided_at:now}).eq('user_id',uid).neq('status','rejected');await s.from('career_profile_photo_settings').upsert({user_id:uid,selected_kind:'original',selected_variant_id:null,updated_at:now},{onConflict:'user_id'});if(old?.storage_object_path&&old.storage_object_path!==path)await s.storage.from(BUCKET).remove([old.storage_object_path]);await audit(s,uid,row.id,'uploaded','USER_CONFIRMED',{mime_type:k.mime,size_bytes:f.size,professional_variants_reset:true});const url=await sign(s,path);return j(201,{status:'PHOTO_READY',photo:{url,mime_type:k.mime,size_bytes:f.size,updated_at:row.updated_at},original_photo:{url,mime_type:k.mime,size_bytes:f.size,updated_at:row.updated_at},selected_kind:'original',matching_usage:false,identity_disclosure:false});
});