import { createClient } from "jsr:@supabase/supabase-js@2.114.0";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-lsi-research-secret","Access-Control-Allow-Methods":"POST, OPTIONS"};
const MAX_DESCRIPTION=12000,MAX_SOURCE_JOBS=500;
function json(status:number,body:Record<string,unknown>){return new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}})}
function clean(v:unknown,max=500){if(v===null||v===undefined)return null;const s=String(v).replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim();return s?s.slice(0,max):null}
function decodeHtml(s:string){return s.replace(/<br\s*\/?\s*>/gi,"\n").replace(/<\/p>/gi,"\n").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g," ").trim().slice(0,MAX_DESCRIPTION)}
function norm(s:string){return s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function workModel(...parts:any[]){const s=norm(parts.filter(Boolean).join(" "));if(/\bremote\b|\bremoto\b/.test(s))return"remote";if(/\bhybrid\b|\bhibrid/.test(s))return"hybrid";if(/\bonsite\b|on-site|in.office|presencial/.test(s))return"onsite";return"unknown"}
function countryCode(raw:string|null,title:string|null){const s=norm(`${raw||""} ${title||""}`);if(/\bbrazil\b|\bbrasil\b|sao paulo|rio de janeiro|belo horizonte|curitiba|porto alegre|brasilia/.test(s))return"BR";if(/\bmexico\b|mexico city/.test(s))return"MX";if(/\bargentina\b|buenos aires/.test(s))return"AR";if(/\bcolombia\b|bogota/.test(s))return"CO";if(/\bchile\b|santiago/.test(s))return"CL";if(/\bperu\b|lima/.test(s))return"PE";if(/\bspain\b|madrid|barcelona/.test(s))return"ES";if(/united states|\busa\b|san francisco|new york|texas|florida/.test(s))return"US";return"XX"}
function locationParts(raw:string|null){const s=raw||"",n=norm(s);if(n.includes("sao paulo"))return{city:"São Paulo",state_code:"SP"};if(n.includes("rio de janeiro"))return{city:"Rio de Janeiro",state_code:"RJ"};if(n.includes("belo horizonte"))return{city:"Belo Horizonte",state_code:"MG"};if(n.includes("curitiba"))return{city:"Curitiba",state_code:"PR"};if(n.includes("porto alegre"))return{city:"Porto Alegre",state_code:"RS"};if(n.includes("brasilia"))return{city:"Brasília",state_code:"DF"};return{city:clean(s,100),state_code:null}}
function regionRelevant(title:string,location:string,description:string){const primary=norm(`${title} ${location}`);if(/\bbrazil\b|\bbrasil\b|sao paulo|rio de janeiro|belo horizonte|curitiba|porto alegre|brasilia|\blatam\b|latin america/.test(primary))return true;const d=norm(description.slice(0,5000));return /(based in brazil|located in brazil|role.{0,50}brazil|position.{0,50}brazil|work.{0,30}from brazil|remote.{0,30}brazil|brazil.{0,30}remote|based in latin america|latam.?based|role.{0,40}latam|position.{0,40}latam)/.test(d)}
async function sha(text:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function dateIso(v:any){if(!v)return null;try{const d=typeof v==="number"?new Date(v):new Date(String(v));return Number.isNaN(d.getTime())?null:d.toISOString()}catch{return null}}
async function fetchJson(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{headers:{Accept:"application/json","User-Agent":"LSI-Career360-Pilot/1.0"},signal:c.signal});if(!r.ok)throw Object.assign(new Error(`HTTP_${r.status}`),{httpStatus:r.status});return await r.json()}finally{clearTimeout(t)}}
async function auth(req:Request,service:any,url:string,anon:string){const cron=req.headers.get("x-lsi-research-secret");if(cron){const{data,error}=await service.rpc("career_validate_research_cron_secret",{p_secret:cron});if(!error&&data===true)return{mode:"cron",user:null};return null}const h=req.headers.get("Authorization");if(!h?.startsWith("Bearer "))return null;const uc=createClient(url,anon,{global:{headers:{Authorization:h}},auth:{persistSession:false,autoRefreshToken:false}});const{data,error}=await uc.auth.getUser();if(error||!data.user)return null;const{data:rr}=await service.from("career_user_roles").select("role").eq("user_id",data.user.id).maybeSingle();if(rr?.role!=="master")return null;return{mode:"master",user:data.user}}

async function sourceJobs(provider:string,key:string){
  if(provider==="greenhouse"){const d:any=await fetchJson(`https://boards-api.greenhouse.io/v1/boards/${encodeURIComponent(key)}/jobs?content=true`);const jobs=Array.isArray(d?.jobs)?d.jobs:[];return{full:true,jobs:jobs.map((j:any)=>({id:String(j.id??""),title:clean(j.title,180)||"",location:clean(j.location?.name,180)||"",url:clean(j.absolute_url,1200),description:decodeHtml(String(j.content||"")),department:clean(j.departments?.[0]?.name,120),published_at:dateIso(j.first_published||j.updated_at),raw_comp:null}))}}
  if(provider==="ashby"){const d:any=await fetchJson(`https://api.ashbyhq.com/posting-api/job-board/${encodeURIComponent(key)}?includeCompensation=true`);const jobs=Array.isArray(d?.jobs)?d.jobs:[];return{full:true,jobs:jobs.filter((j:any)=>j?.isListed!==false).map((j:any)=>({id:String(j.id||j.jobUrl||""),title:clean(j.title,180)||"",location:clean(j.location,180)||"",url:clean(j.jobUrl||j.applyUrl,1200),description:decodeHtml(String(j.descriptionPlain||j.descriptionHtml||j.description||"")),department:clean(j.department||j.team,120),published_at:dateIso(j.publishedAt),raw_comp:clean(j.compensation?.scrapeableCompensationSalarySummary||j.compensation?.compensationTierSummary,500),workplace:j.workplaceType}))}}
  if(provider==="lever"){let out:any[]=[],skip=0;while(out.length<MAX_SOURCE_JOBS){const page:any=await fetchJson(`https://api.lever.co/v0/postings/${encodeURIComponent(key)}?mode=json&skip=${skip}&limit=100`);if(!Array.isArray(page))break;out.push(...page);if(page.length<100)break;skip+=100}const full=out.length<MAX_SOURCE_JOBS;return{full,jobs:out.slice(0,MAX_SOURCE_JOBS).map((j:any)=>({id:String(j.id||""),title:clean(j.text,180)||"",location:clean(j.categories?.location,180)||"",url:clean(j.hostedUrl||j.applyUrl,1200),description:clean(j.descriptionPlain||decodeHtml(String(j.description||"")),MAX_DESCRIPTION)||"",department:clean(j.categories?.department||j.categories?.team,120),published_at:dateIso(j.createdAt),raw_comp:clean(j.salaryRange?JSON.stringify(j.salaryRange):null,500),workplace:j.workplaceType}))}}
  throw new Error("PROVIDER_NOT_SUPPORTED")
}

Deno.serve(async(req)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
  if(req.method!=="POST")return json(405,{error:"METHOD_NOT_ALLOWED"});
  const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!anon||!serviceKey)return json(500,{error:"SERVER_CONFIG_ERROR"});
  const service:any=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}}),actor=await auth(req,service,url,anon);if(!actor)return json(401,{error:"RESEARCH_AUTH_REQUIRED"});
  let body:any={};try{body=await req.json()}catch{}const sourceLimit=Math.max(1,Math.min(5,Number(body?.source_limit)||3));
  const{data:ctl,error:ctlErr}=await service.from("career_engine_control").select("champion_version,rollback_version,status").eq("component","matching").maybeSingle();if(ctlErr)return json(503,{error:"MATCHING_ENGINE_READ_FAILED"});
  const engine=ctl?.status==="active"&&ctl?.champion_version?String(ctl.champion_version):"v2.0";
  const rollbackEngine=ctl?.rollback_version?String(ctl.rollback_version):null;
  const{data:sources,error:sErr}=await service.from("career_opportunity_sources").select("id,provider,source_key,employer_name,priority,last_checked_at,consecutive_failures").eq("active",true).order("last_checked_at",{ascending:true,nullsFirst:true}).order("priority",{ascending:true}).limit(sourceLimit);if(sErr)return json(503,{error:"SOURCE_READ_FAILED"});
  const{data:profiles}=await service.from("career_profiles").select("user_id").eq("onboarding_status","agent_ready").limit(100);const users=(profiles||[]).map((x:any)=>x.user_id);
  let searchPlansReady=0;for(const uid of users){const{error}=await service.rpc("career_build_role_search_plan",{p_user_id:uid,p_persist:true});if(!error)searchPlansReady++}
  const summary:any[]=[];

  for(const src of sources||[]){
    const started=new Date().toISOString(),sourceName=`ats:${src.provider}:${src.source_key}`;
    const{data:run}=await service.from("career_opportunity_research_runs").insert({source_id:src.id,status:"running",metadata_safe:{actor:actor.mode,source_name:sourceName,matching_engine:engine,rollback_engine:rollbackEngine,role_search_plan:"role-search-v2",filter_version:"region-v2"}}).select("id").single();
    let fetched=0,accepted=0,deduped=0,expired=0,matched=0,httpStatus=null,errorCode=null;
    try{
      const snap:any=await sourceJobs(src.provider,src.source_key);fetched=snap.jobs.length;
      for(const j of snap.jobs){
        if(!j.title||!j.id)continue;if(!regionRelevant(j.title,j.location,j.description))continue;
        const fp=await sha(`${src.provider}|${src.source_key}|${j.id}`),sourceHash=await sha(JSON.stringify({t:j.title,l:j.location,u:j.url,d:j.description,dep:j.department,w:j.workplace,c:j.raw_comp}));
        const{data:existing}=await service.from("career_opportunities").select("id,source_hash,status").eq("source_name",sourceName).eq("source_job_id",j.id).maybeSingle();
        const lp=locationParts(j.location),wm=workModel(j.workplace,j.location,j.description),cc=countryCode(j.location,j.title);
        const payload:any={source_name:sourceName,source_job_id:j.id,source_url:j.url,employer_name:src.employer_name,title:j.title,description_text:j.description||null,sector:j.department,city:lp.city,state_code:lp.state_code,country_code:cc,work_model:wm,salary_min:null,salary_max:null,salary_currency:"BRL",salary_evidence_class:j.raw_comp?"estimated":"hidden",required_skills:[],preferred_skills:[],evidence_safe:{provider:src.provider,public_feed:true,raw_location:j.location||null,compensation_summary:j.raw_comp||null,source_key:src.source_key,region_filter:"v2"},published_at:j.published_at,fetched_at:new Date().toISOString(),expires_at:null,status:"active",dedupe_fingerprint:fp,last_seen_at:new Date().toISOString(),source_hash:sourceHash,updated_at:new Date().toISOString()};
        let oppId=existing?.id;const changed=!existing||existing.source_hash!==sourceHash||existing.status!=="active";
        if(existing){const{error}=await service.from("career_opportunities").update(payload).eq("id",existing.id);if(error)throw new Error("OPPORTUNITY_UPDATE_FAILED");if(!changed)deduped++}
        else{const{data:newOpp,error}=await service.from("career_opportunities").insert(payload).select("id").single();if(error||!newOpp)throw new Error("OPPORTUNITY_INSERT_FAILED");oppId=newOpp.id;accepted++}
        if(changed&&oppId){for(const uid of users){const{error}=await service.rpc("career_score_opportunity",{p_user_id:uid,p_opportunity_id:oppId,p_persist:true});if(!error)matched++}}
      }
      if(snap.full){const{data:old}=await service.from("career_opportunities").update({status:"expired",updated_at:new Date().toISOString()}).eq("source_name",sourceName).eq("status","active").lt("last_seen_at",started).select("id");const oldIds=(old||[]).map((x:any)=>x.id);expired=oldIds.length;if(oldIds.length)await service.from("career_matches").update({score:null,classification:"EXPIRED",salary_state:"UNKNOWN",breakdown:{gate:"OPPORTUNITY_EXPIRED"},explanation_safe:{message:"A oportunidade não está mais ativa."},updated_at:new Date().toISOString()}).in("opportunity_id",oldIds)}
      await service.from("career_opportunity_sources").update({last_checked_at:new Date().toISOString(),last_success_at:new Date().toISOString(),consecutive_failures:0,last_error_code:null,updated_at:new Date().toISOString()}).eq("id",src.id);
      await service.from("career_opportunity_research_runs").update({status:snap.full?"success":"partial",finished_at:new Date().toISOString(),fetched_count:fetched,accepted_count:accepted,deduped_count:deduped,expired_count:expired,matched_users:matched,metadata_safe:{actor:actor.mode,source_name:sourceName,full_snapshot:snap.full,matching_engine:engine,rollback_engine:rollbackEngine,champion_match_operations:matched,role_search_plan:"role-search-v2",filter_version:"region-v2"}}).eq("id",run.id)
    }catch(e:any){
      errorCode=clean(e?.message,120)||"RESEARCH_FAILED";httpStatus=Number(e?.httpStatus)||null;
      await service.from("career_opportunity_sources").update({last_checked_at:new Date().toISOString(),consecutive_failures:(Number(src.consecutive_failures)||0)+1,last_error_code:errorCode,updated_at:new Date().toISOString()}).eq("id",src.id);
      if(run?.id)await service.from("career_opportunity_research_runs").update({status:"failed",finished_at:new Date().toISOString(),fetched_count:fetched,accepted_count:accepted,deduped_count:deduped,expired_count:expired,matched_users:matched,error_code:errorCode,http_status:httpStatus,metadata_safe:{actor:actor.mode,source_name:sourceName,matching_engine:engine,rollback_engine:rollbackEngine,role_search_plan:"role-search-v2",filter_version:"region-v2"}}).eq("id",run.id)
    }
    summary.push({provider:src.provider,employer:src.employer_name,fetched,accepted,deduped,expired,champion_match_operations:matched,error:errorCode})
  }
  return json(200,{status:"RESEARCH_CYCLE_COMPLETE",actor:actor.mode,matching_engine:engine,rollback_engine:rollbackEngine,role_search_plan:"role-search-v2",search_plans_ready:searchPlansReady,filter_version:"region-v2",sources:summary,agent_ready_users:users.length});
});
