#!/usr/bin/env python3
from __future__ import annotations

import datetime as dt
import importlib.util
import json
import os
from pathlib import Path
from urllib.parse import quote

import requests

ROOT = Path(__file__).resolve().parents[1]
PROD_PATH = ROOT / "scripts" / "ugi_instagram_production_20260831.py"
spec = importlib.util.spec_from_file_location("ig31", PROD_PATH)
prod = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(prod)

OUT = ROOT / "control-plane" / "emergency-routing" / "ugi-20260831-media-map.json"
WORKER = prod.WORKER

COMMANDS = {
    "UGI-20260831-TT-CURSOR-OPENAI": "control-plane/commands/ugi-20260831-tiktok-cursor-openai.json",
    "UGI-20260831-YT-GOOGLE-AI-OVERVIEWS": "control-plane/commands/ugi-20260831-youtube-google-ai-overviews.json",
    "UGI-20260831-IG-REEL-VW-CHANGE": "control-plane/commands/ugi-20260831-instagram-volkswagen-change.json",
    "UGI-20260831-YT-NVIDIA-INFRA": "control-plane/commands/ugi-20260831-youtube-nvidia-ai-infrastructure.json",
    "UGI-20260831-TT-AI-CYBER": "control-plane/commands/ugi-20260831-tiktok-ai-cyber.json",
}


def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    key = os.environ.get("UGI_WORKER_COMMAND_KEY") or os.environ.get("UGI_LOLA_COMMAND_KEY")
    if not key:
        raise RuntimeError("missing UGI worker key")
    headers = {"x-lola-command-key": key, "accept": "application/json"}
    client = prod.Client(key)
    payload = {
        "project": "UGI",
        "component": "EMERGENCY-MEDIA-MAP-20260831",
        "generatedAt": dt.datetime.now(dt.timezone.utc).isoformat(),
        "instagram": [],
        "platformVideos": [],
    }

    # Upload the exact AV files generated by the canonical Instagram production script.
    for i, story in enumerate(prod.STORIES, 1):
        video = prod.ASSET_DIR / f"story-{i:02d}.mp4"
        pr = prod.probe(video)
        if not pr.get("video") or not pr.get("audio"):
            raise RuntimeError(f"instagram_story_av_fail:{story['id']}")
        up = prod.upload_video(client, story["id"] + "-EMERGENCY", video)
        url = up.get("videoUrl")
        if not url:
            raise RuntimeError(f"instagram_story_upload_no_url:{story['id']}")
        payload["instagram"].append({
            "contentId": story["id"],
            "type": "story",
            "videoUrl": url,
            "music": story["music"],
            "canonicalDue": story["due"],
            "recoveryDue": "2026-08-31T10:45:00-03:00" if i == 1 else story["due"],
            "avQA": pr,
        })

    carousel_video = prod.ASSET_DIR / "carousel-01.mp4"
    carousel_up = prod.upload_video(client, prod.CAROUSEL["id"] + "-EMERGENCY", carousel_video)
    carousel_video_url = carousel_up.get("videoUrl")
    if not carousel_video_url:
        raise RuntimeError("carousel_upload_no_url")
    payload["instagram"].append({
        "contentId": prod.CAROUSEL["id"],
        "type": "carousel",
        "due": prod.CAROUSEL["due"],
        "caption": prod.CAROUSEL["caption"],
        "media": [carousel_video_url] + [f"{prod.RAW_BASE}/carousel-{i:02d}.png" for i in range(2, 8)],
        "music": prod.CAROUSEL["music"],
    })

    manifest = load(ROOT / "control-plane/publisher-hub/queue/ugi-20260831-platform-video-agenda.json")
    for row in manifest["posts"]:
        cid = row["contentId"]
        plat = row["platform"]
        state = load(ROOT / "control-plane/publisher-hub/render-state" / f"{cid}.json")
        render_id = state.get("workerRenderId")
        if not render_id:
            raise RuntimeError(f"missing_render_id:{cid}")
        r = requests.get(WORKER + "/api/video-result/" + quote(str(render_id)), headers=headers, timeout=120)
        data = r.json()
        asset = (data.get("assets") or {}).get(plat) or {}
        if r.status_code != 200 or data.get("ok") is not True or asset.get("ready") is not True or not asset.get("videoUrl"):
            raise RuntimeError(f"platform_video_not_ready:{cid}:{r.status_code}:{data}")
        cmd = load(ROOT / COMMANDS[cid])
        scenes = cmd.get("scenes_json") or {}
        payload["platformVideos"].append({
            "contentId": cid,
            "platform": plat,
            "dueAt": row["dueAt"],
            "videoUrl": asset["videoUrl"],
            "title": cmd.get("title"),
            "cta": scenes.get("cta"),
            "renderId": render_id,
            "videoStatus": data.get("status"),
        })

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
